// ZPHC Türkiye ürün kataloğu.
//
// Bu dosya zphcstore.com WooCommerce Store API'sinden üretilmiştir
// (scripts/gen-products.py). Teknik değerler — mg, IU, flakon sayısı,
// saklama sıcaklığı — kaynaktan olduğu gibi taşınır. Hiçbir doz değeri
// elle türetilmez veya tahmin edilmez: ürün sayfasındaki yanlış bir doz
// doğrudan güvenlik sorunudur. Veriyi güncellemek için üreteci yeniden
// çalıştır, elle düzenleme yapma.
//
// Kaynak, ürünleri laboratuvar/araştırma materyali olarak sunar
// ("for research use only"). Bu çerçeve sitede korunur.
//
// sourcePriceUsd kaynak sitedeki USD listesidir, referans içindir.
// Sitede gösterilen fiyat alanı (price) bilinçli olarak boştur.

export type ProductCategory = "peptid" | "hgh" | "aksesuar"

export const categoryLabels: Record<ProductCategory, string> = {
  peptid: "Peptidler",
  hgh: "İnsan Büyüme Hormonu",
  aksesuar: "Aksesuar",
}

export const categoryOrder: ProductCategory[] = ["peptid", "hgh", "aksesuar"]

export interface ProductSpec {
  label: string
  value: string
}

export interface Product {
  slug: string
  name: string
  sku?: string
  category: ProductCategory
  /** lib/peptides.ts içindeki ansiklopedi kaydı; doluysa ürün sayfası
   * mekanizma, kanıt seviyesi ve PubMed referanslarını oradan çeker. */
  peptideSlug?: string
  image?: string
  /** Kaynak sitedeki USD fiyatı. Referans; sayfada gösterilmez. */
  sourcePriceUsd?: number
  /** Sitede gösterilecek fiyat. Şimdilik boş. */
  price?: string
  specs: ProductSpec[]
  notes: string[]
}

export const products: Product[] = [
  {
    slug: "aicar-250mg-total-5x50mg-zphc",
    name: "AICAR ZPHC — 250 mg (5 vials × 50 mg)",
    sku: "AIC250-ZPHC",
    category: "peptid",
    peptideSlug: "aicar",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/aicar-50mg-vial-250mg-kit-zphc-1.jpg",
    sourcePriceUsd: 79.0,
    specs: [],
    notes: [],
  },
  {
    slug: "aod-9604-5mg-with-bacteriostatic-water-zphc",
    name: "AOD 9604 5mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "AOD9604-5-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/aod-9604-5mg-vial-zphc-1.jpg",
    sourcePriceUsd: 31.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 5mg lyophilized AOD 9604 peptide + 1 vial bacteriostatic water for reconstitution." },
      { label: "Peptid Profili", value: "modified fragment of human growth hormone (HGH 176–191), laboratory-grade synthetic peptide." },
      { label: "Rekonstitüsyon", value: "add supplied diluent under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "lipolysis models, adipose tissue studies, metabolic pathway research and weight-regulation analysis." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-verified and authenticity-protected; for research use only." },
    ],
    notes: [
      "AOD 9604 5mg — Synthetic Growth Hormone Fragment",
      "Lyophilized Powder + Bacteriostatic Water",
    ],
  },
  {
    slug: "aod9604-2-5mg-5x2-5mg-zphc",
    name: "AOD 9604 ZPHC — 12.5 mg (5 vials × 2.5 mg)",
    sku: "AOD125-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/AOD-9604-12.5mg-kit-zphc-2.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Mechanism", value: "fragment 176-191 analogue that boosts lipolysis and blocks lipogenesis without raising IGF-1 or blood glucose." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 2.5 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C after mixing; freeze-dried powder ships safely at room temperature." },
      { label: "Örnek Araştırma Dozu", value: "250 – 500 µg sub-Q daily (split AM/PM) for 4 – 6 weeks." },
    ],
    notes: [
      "AOD 9604 — targeted fat-loss peptide",
      "5 lyophilised vials × 2.5 mg (total 12.5 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; scratch-code authenticity on every box.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "aod9604-25mg-5x5mg-zphc",
    name: "AOD 9604 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "AOD25-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/AOD-9604-25mg-kit-zphc-1.jpg",
    sourcePriceUsd: 125.0,
    specs: [
      { label: "Mechanism", value: "fragment 176-191 analogue that boosts lipolysis and inhibits lipogenesis without elevating glucose or IGF-1." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 5 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C after mixing; freeze-dried powder is RT-stable during shipping." },
      { label: "Örnek Araştırma Dozu", value: "250 – 500 µg sub-Q daily (split AM/PM) for 4 – 6 weeks." },
    ],
    notes: [
      "AOD 9604 — targeted fat-loss peptide",
      "5 lyophilised vials × 5 mg (total 25 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; each box carries a scratch-code for authenticity.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "zphc-bpc-157-20mg-with-bacteriostatic-water",
    name: "BPC-157 20mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "BPC157-20-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/bpc-157-20mg-vial-zphc-1.jpg",
    sourcePriceUsd: 83.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 20mg lyophilized BPC-157 peptide + 1 vial sterile diluent for reconstitution." },
      { label: "Peptid Profili", value: "BPC-157 (Body Protection Compound), laboratory-grade synthetic peptide." },
      { label: "Rekonstitüsyon", value: "add supplied diluent under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "tissue-repair models, angiogenesis studies, gastrointestinal research, cellular regeneration pathways." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-verified and authenticity-controlled; for research use only." },
    ],
    notes: [
      "BPC-157 20mg — Synthetic Peptide",
      "Lyophilized Powder + Sterile Diluent",
    ],
  },
  {
    slug: "bpc157-25mg-5x5mg-zphc",
    name: "BPC-157 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "BPC15725-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/BPC-157-25mg-Kit-ZPHC-2.jpg",
    sourcePriceUsd: 99.0,
    specs: [
      { label: "Rapid tissue repair", value: "peptide accelerates healing of tendons, ligaments, muscle and GI lining." },
      { label: "Anti-inflammatory support", value: "helps reduce pain and swelling while boosting collagen synthesis." },
      { label: "Liyofilize Saflık", value: "reconstitute each 5 mg vial with 1–2 ml bacteriostatic water for clear solution." },
      { label: "Doz Rehberi", value: "200–500 mcg sub-Q near injury site 1–2 × daily for 4–6 weeks; refrigerate reconstituted vial." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free; scratch-code authenticity." },
    ],
    notes: [
      "Pharma-grade BPC-157 – 5 vials × 5 mg (total 25 mg)",
      "Insulated worldwide shipping • discreet packaging • multilingual support.",
    ],
  },
  {
    slug: "cagrilintide-25mg-zphc",
    name: "Cagrilintide (25mg) ZPHC",
    sku: "CAGRI25-ZPHC",
    category: "peptid",
    peptideSlug: "cagrilintide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/Cagrilintide-25mg-KIT-ZPHC-3.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Amylin receptor analogue", value: "researched for potent appetite suppression and reduced caloric intake." },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥ 98.9% purity (HPLC); produced under GMP & ISO 17034:2016 standards with ZPHC scratch-code verification." },
      { label: "Rekonstitüsyon", value: "combine with sterile diluent provided; swirl gently until dissolved. Store at 2–8 °C." },
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for therapeutic or human use." },
    ],
    notes: [
      "Cagrilintide — ZPHC Pro-Line",
      "5 lyophilised vials × 5 mg (total 25 mg) + sterile diluent",
      "Satiety & gastric emptying: enhances fullness signals and slows gastric emptying for improved weight-management outcomes.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "double-burn-mix-5mg-5x5mg-zphc",
    name: "Double Burn Mix ZPHC — 25 mg total (5 vials × 5 mg)",
    sku: "DOU25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/double-burn-mix-25mg-kit-zphc-7.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Flakon Başına Formül", value: "AOD 9604 2.5 mg · FRAG 176-191 2.5 mg." },
      { label: "Synergistic action", value: "both fragments target adipose tissue, accelerating lipolysis while blocking new fat storage — no IGF-1 or glucose spikes." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 5 mg/ml; swirl gently, avoid foam." },
      { label: "Saklama", value: "refrigerate 2–8 °C after mixing; freeze-dried powder ships safely at room temp." },
      { label: "Örnek Araştırma Dozu", value: "250–500 µg sub-Q once or twice daily 30 min pre-cardio, course 4–6 weeks." },
    ],
    notes: [
      "Double Burn Mix — dual-pathway fat-loss peptide",
      "5 lyophilised vials × 5 mg (total 25 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; scratch-code authenticity on every box.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "epithalon-50mg-with-bacteriostatic-water-zphc",
    name: "Epithalon 50mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "EPITH50-ZPHC",
    category: "peptid",
    peptideSlug: "epithalon",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/EPITHALON-50MG-VIAL-ZPHC-8.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 50mg lyophilized Epithalon + 1 vial sterile diluent for reconstitution." },
      { label: "Peptid Profili", value: "Epithalon (Epitalon), synthetic tetrapeptide (Ala-Glu-Asp-Gly), laboratory-grade material." },
      { label: "Rekonstitüsyon", value: "add supplied diluent under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "telomerase activity studies, cellular aging models, circadian rhythm research, antioxidant pathway analysis." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; protect from light." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-tracked and authenticity-verified; for research use only." },
    ],
    notes: [
      "Epithalon 50mg — Synthetic Tetrapeptide",
      "Lyophilized Powder + Sterile Diluent",
    ],
  },
  {
    slug: "ghk-cu-60mg-with-bacteriostatic-water-zphc",
    name: "GHK-Cu 60mg Kit ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "GHKCU60-ZPHC",
    category: "peptid",
    peptideSlug: "ghk-cu",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/GHK-CU-60MG-KIT-1VIAL-ZPHC-3.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 60mg lyophilized GHK-Cu (copper peptide) + 1 vial bacteriostatic water for reconstitution." },
      { label: "Peptid Profili", value: "GHK-Cu (glycyl-L-histidyl-L-lysine copper complex), synthetic laboratory-grade peptide." },
      { label: "Rekonstitüsyon", value: "add supplied bacteriostatic water under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "collagen synthesis models, tissue-regeneration studies, skin-repair pathways, anti-inflammatory research." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; protect from light." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-verified and authenticity-controlled; for research use only." },
    ],
    notes: [
      "GHK-Cu 60mg — Copper Peptide",
      "Lyophilized Powder + Bacteriostatic Water",
    ],
  },
  {
    slug: "ghk-cu-50mg-zphc",
    name: "GHK-Cu ZPHC — 50 mg KIT (5 vials × 10 mg)",
    sku: "GHKCU50-ZPHC",
    category: "peptid",
    peptideSlug: "ghk-cu",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/GHK-CU-50MG-KIT-5VIAL-ZPHC-1.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Regenerative copper peptide", value: "researched for enhanced skin repair, collagen stimulation and improved dermal structure." },
      { label: "Anti-aging activity", value: "supports cellular renewal, elasticity restoration and reduction of visible aging markers." },
      { label: "Hair-growth support", value: "promotes follicle health and may assist in research protocols targeting hair density." },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥ 98.9% purity (HPLC); produced under GMP & ISO 17034:2016 with ZPHC scratch-code authentication." },
      { label: "Rekonstitüsyon", value: "add sterile diluent provided; swirl gently until dissolved. Store at 2–8 °C." },
    ],
    notes: [
      "GHK-Cu (Copper Tripeptide-1) — ZPHC",
      "5 lyophilised vials × 10 mg (total 50 mg) + sterile diluent",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "ghrp-2-25mg-5x5mg-zphc-2",
    name: "GHRP-2 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "GHRP225-ZPHC",
    category: "peptid",
    peptideSlug: "ghrp-2",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/GHRP-2-25mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "GH pulse amplifier", value: "potent ghrelin-receptor peptide boosts pituitary growth-hormone release." },
      { label: "Doz Rehberi", value: "100 – 300 mcg sub-Q 2-3× daily (pre-bed & post-workout) for 6-8 weeks; refrigerate reconstituted vial." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free; scratch-code authenticity." },
    ],
    notes: [
      "Pharma-grade GHRP-2 – 5 vials × 5 mg (total 25 mg)",
      "Recovery & fat-loss: supports muscle repair, improves sleep quality and enhances lipolysis.",
      "Pure 5 mg lyophilized vials: reconstitute with 2 ml bacteriostatic water for 2,500 mcg/ml solution.",
      "Temperature-controlled shipping • discreet packaging • tracked worldwide delivery.",
    ],
  },
  {
    slug: "ghrp-6-25mg-5x5mg-zphc",
    name: "GHRP-6 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "GHRP625-ZPHC",
    category: "peptid",
    peptideSlug: "ghrp-6",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/GHRP-6-25mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [],
    notes: [],
  },
  {
    slug: "glow-pro-mix-60mg-bpc157-tb500-ghkcu-zphc",
    name: "Glow Pro Mix 60mg ZPHC - (BPC-157 + TB-500 + GHK-Cu)",
    sku: "GLOWMIX-60-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/glow-pro-mix-60mg-zphc-1.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 60mg lyophilized peptide blend + 1 vial bacteriostatic water for reconstitution." },
      { label: "Peptid Profili", value: "combination of BPC-157, TB-500 (Thymosin Beta-4 fragment) and GHK-Cu (copper peptide)." },
      { label: "Rekonstitüsyon", value: "add supplied bacteriostatic water under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "tissue-repair studies, collagen synthesis models, skin-regeneration pathways, recovery and angiogenesis research." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-verified and authenticity-controlled; for research use only." },
    ],
    notes: [
      "Glow Pro Mix 60mg — Advanced Peptide Blend",
      "BPC-157 + TB-500 + GHK-Cu",
    ],
  },
  {
    slug: "hgh-fragment-176-191-50mg-5x10mg-zphc",
    name: "HGH FRAGMENT 176-191aa (50MG) ZPHC",
    sku: "HGHF50-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/hgh-fragment-10mg-vial-50mg-kit-ZPHC-7.jpg",
    sourcePriceUsd: 147.0,
    specs: [
      { label: "Selective fat-loss", value: "fragment 176-191 enhances lipolysis and blocks lipogenesis without raising glucose or IGF-1." },
      { label: "Rekonstitüsyon", value: "add 2 ml bacteriostatic water → 5 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C once mixed; freeze-dried powder ships safely at room temperature." },
      { label: "Örnek Araştırma Dozu", value: "250 – 500 µg sub-Q 1–3 × daily, 30 min pre-cardio, for 4–6 weeks." },
    ],
    notes: [
      "HGH Fragment 176-191 — targeted lipolytic peptide",
      "5 lyophilised vials × 10 mg (total 50 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; scratch-code authenticity on every box.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "zphc-hgh-fragment-176-191-5mg",
    name: "HGH Fragment 176-191 5mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "HGHFRAG-5-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/HGH-fragment-5mg-vial-5mg-kit-ZPHC-3.jpg",
    sourcePriceUsd: 29.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 5mg lyophilized HGH Fragment 176-191 + 1 vial sterile diluent for reconstitution." },
      { label: "Peptid Profili", value: "synthetic fragment of human growth hormone (amino acids 176–191), laboratory-grade material." },
      { label: "Rekonstitüsyon", value: "add supplied diluent under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "lipolysis models, metabolic pathway studies, adipose-tissue research and energy-regulation analysis." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile vial, batch-verified and authenticity-controlled; for research use only." },
    ],
    notes: [
      "HGH Fragment 176-191 5mg — Growth Hormone Fragment",
      "Lyophilized Peptide + Sterile Diluent",
    ],
  },
  {
    slug: "hgh-fragment-176-191-12-5mg-5x2-5mg-zphc",
    name: "HGH Fragment 176-191 ZPHC — 12.5 mg (5 vials × 2.5 mg)",
    sku: "HGHF125-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/HGH-fragment-5mg-vial-25mg-kit-ZPHC-8.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Targeted fat-loss", value: "fragment 176-191 triggers lipolysis without raising blood sugar or IGF-1." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 2.5 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C after mixing; freeze-dried powder ships safely at room temp." },
      { label: "Örnek Araştırma Dozu", value: "250 – 500 µg sub-Q 1–3× daily, 30 min pre-cardio, for 4 – 6 weeks." },
    ],
    notes: [
      "HGH Fragment 176-191 — selective lipolytic peptide",
      "5 lyophilised vials × 2.5 mg (total 12.5 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; box with scratch-code authenticity.",
      "Cold-chain packed · tamper-evident vials · discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "hgh-fragment-176-191-25mg-5x5mg-zphc",
    name: "HGH Fragment 176-191 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "HGHF25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/HGH-fragment-5mg-vial-25mg-kit-ZPHC-8-1.jpg",
    sourcePriceUsd: 125.0,
    specs: [
      { label: "Selective fat-loss", value: "fragment 176-191 increases lipolysis and inhibits lipogenesis without raising blood glucose or IGF-1." },
      { label: "Rekonstitüsyon", value: "add 2 ml bacteriostatic water → 2.5 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C after mixing; freeze-dried powder is stable during room-temperature shipping." },
      { label: "Örnek Araştırma Dozu", value: "250 – 500 µg sub-Q 1-3 × daily, 30 min pre-cardio, for 4 – 6 weeks." },
    ],
    notes: [
      "HGH Fragment 176-191 — targeted lipolytic peptide",
      "5 lyophilised vials × 5 mg (total 25 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; scratch-code authenticity on every box.",
      "Cold-chain packed · tamper-evident vials · discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "hp-hcg-5000iu-vial-zphc",
    name: "HP-hCG ZPHC — 5 000 IU (1 lyophilized vial)",
    sku: "HCG5000-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2023/05/hp-hcg.jpg",
    sourcePriceUsd: 55.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Human Chorionic Gonadotropin (hCG)" },
      { label: "Konsantrasyon", value: "5000 IU per vial" },
      { label: "Hacim", value: "1 vial, each with 5000 IU" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Hormone therapy, PCT, treatment of infertility in men and women, and regulation of testosterone production" },
      { label: "Etki", value: "Stimulates the production of testosterone in men and supports ovulation in women. Helps in the maintenance of pregnancy in early stages and can assist in weight loss protocols." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injections after reconstitution" },
      { label: "Önerilen Doz", value: "As prescribed by a healthcare professional, typically used in PCT or as part of fertility treatments" },
      { label: "Yan Etkiler", value: "Possible headaches, irritability, restlessness, depression, swelling, and potential allergic reactions" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "hp-hcg-1000iu-zphc",
    name: "HP-hCG ZPHC — 5 000 IU kit (5 vials × 1 000 IU)",
    sku: "HCG1000-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2023/12/hp-hcg-1000-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Human Chorionic Gonadotropin (hCG)" },
      { label: "Konsantrasyon", value: "1000 IU per vial" },
      { label: "Hacim", value: "5 vials" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Hormone therapy, treatment of infertility, post-cycle therapy (PCT)" },
      { label: "Etki", value: "Stimulates testosterone production, supports fertility, aids in hormone regulation during and after anabolic steroid cycles" },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injection after reconstitution" },
      { label: "Önerilen Doz", value: "As prescribed by a healthcare professional, typically used in PCT or as part of fertility treatments" },
      { label: "Yan Etkiler", value: "Possible side effects include headaches, irritability, restlessness, and potential allergic reactions" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "igf1-lr3-1mg-5x0p2mg-zphc",
    name: "IGF-1 LR3 ZPHC — 1 mg (5 vials × 0.2 mg)",
    sku: "IGF1-ZPHC",
    category: "peptid",
    peptideSlug: "igf-1-lr3",
    image: "https://zphcstore.com/wp-content/uploads/2023/08/igf-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Üretici", value: "ZPHC (Zhengzhou Pharmaceutical Co. Ltd)" },
      { label: "Etkin Madde", value: "IGF-1 LR3 (Insulin-like Growth Factor 1 Long R3)" },
      { label: "Konsantrasyon", value: "200 mcg per vial" },
      { label: "Hacim", value: "5 vials" },
      { label: "Form", value: "Lyophilized powder for reconstitution with Bacteriostatic Water" },
      { label: "Kullanım Amacı", value: "Muscle growth, fat metabolism, and anti-aging benefits" },
      { label: "Etki", value: "IGF-1 LR3 promotes muscle growth and development by increasing protein synthesis and nitrogen retention. It also aids in fat metabolism and supports overall body composition improvement. Additionally, it has anti-aging effects by promoting cell regeneration and repair." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injections after reconstitution with Bacteriostatic Water" },
      { label: "Önerilen Doz", value: "Individually prescribed by a healthcare professional" },
      { label: "Yan Etkiler", value: "Possible side effects include hypoglycemia, joint pain, headaches, and swelling" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "ipamorelin-25mg-5x5mg-zphc",
    name: "Ipamorelin ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "IPA25-ZPHC",
    category: "peptid",
    peptideSlug: "ipamorelin",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Ipamorelin-25mg-Kit-ZPHC-3.jpg",
    sourcePriceUsd: 118.0,
    specs: [
      { label: "Growth-hormone boost", value: "selective ghrelin-receptor agonist elevates GH & IGF-1 without cortisol spikes." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free, micro-filtered." },
      { label: "Doz Rehberi", value: "200–300 mcg sub-Q post-workout or pre-bed, 6–8 weeks; refrigerate reconstituted vial." },
    ],
    notes: [
      "Pharma-grade Ipamorelin – 5 vials × 5 mg (total 25 mg)",
      "Recovery & fat-loss: supports lean-muscle retention, deeper REM sleep and accelerated healing.",
      "Sealed vials in tamper-evident box • scratch-code authenticity • tracked worldwide shipping.",
    ],
  },
  {
    slug: "l-glutathione-3000mg-kit-zphc",
    name: "L-Glutathione ZPHC - 3000 mg Kit (5×600 mg Vials + Diluent)",
    sku: "GLUT3000-ZPHC",
    category: "peptid",
    peptideSlug: "glutathione",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/L-GLUTATIONE-3000MG-KIT-ZPHC-5.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Cellular anti-aging support", value: "reduced GSH replenishes intracellular antioxidant capacity and combats oxidative stress markers." },
      { label: "Flexible reconstitution", value: "each 600 mg vial pairs with the included diluent, allowing custom concentration setups for research models." },
      { label: "Stability preserved", value: "nitrogen overlay in all vials protects the thiol group from oxidation during storage and transport." },
      { label: "Research protocol example", value: "600–1200 mg oxidative stress modulation models; synergistic pairing with vitamin C for enhanced redox cycling." },
      { label: "Profi-Line QC", value: "Certified Reference Material (CRM), ≥99% purity (HPLC), sterility & endotoxin approved, scratch-code validation." },
    ],
    notes: [
      "L-Glutathione (Reduced) — pharmaceutical-grade antioxidant tripeptide",
      "5 × 600 mg lyophilized vials + 1 × sterile diluent • 3000 mg total",
      "Refrigerated grade • tamper-evident caps • export-only multi-vial presentation.",
    ],
  },
  {
    slug: "ll-37-zphc-25mg-kit",
    name: "LL-37 ZPHC - 25mg KIT (5×5 mg)",
    sku: "LL37-25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/LL-37-25MG-KIT-ZPHC-3.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Host-defense peptide", value: "LL-37 supports immune modeling, barrier integrity and antimicrobial response in research settings." },
      { label: "Liyofilize Saflık", value: "5 mg freeze-dried vials enable controlled reconstitution for precise peptide dosing." },
      { label: "Stability assured", value: "nitrogen-filled borosilicate vials • sterile matched diluent • CRM-grade synthesis." },
    ],
    notes: [
      "LL-37 — human cathelicidin antimicrobial peptide (AMP)",
      "5 × 5 mg vials • 25 mg total",
      "QC & authenticity: ISO/GMP manufacturing • HPLC ≥99% purity • holographic scratch-code verification.",
    ],
  },
  {
    slug: "mots-c-20mg-with-bacteriostatic-water-zphc",
    name: "MOTS-c 20mg Kit ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "MOTSC-20-ZPHC",
    category: "peptid",
    peptideSlug: "mots-c",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/mots-c-20mg-zphc-1.jpg",
    sourcePriceUsd: 99.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 20mg lyophilized MOTS-c peptide + 1 vial bacteriostatic water for reconstitution." },
      { label: "Peptid Profili", value: "MOTS-c (mitochondrial open reading frame of the 12S rRNA), synthetic laboratory-grade peptide." },
      { label: "Rekonstitüsyon", value: "add supplied bacteriostatic water under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "metabolic regulation studies, mitochondrial function research, glucose metabolism models, cellular energy pathway analysis." },
      { label: "Taşıma ve Muhafaza", value: "store lyophilized powder in a cool, dry place; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "hermetically sealed sterile glass vial, batch-verified and authenticity-controlled; for research use only." },
    ],
    notes: [
      "MOTS-c 20mg — Mitochondrial-Derived Peptide",
      "Lyophilized Powder + Bacteriostatic Water",
    ],
  },
  {
    slug: "mega-mass-mix-10mg-5x10mg-zphc",
    name: "Mega Mass Mix ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "MEG50-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Mega-Mass-50mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Flakon Başına Formül", value: "GHRP-6 5 mg · CJC-1295 5 mg." },
      { label: "Dual action", value: "GHRP-6 triggers ghrelin receptors → sharp GH pulse & hunger spike; CJC-1295 prolongs GHRH signal for sustained GH release." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 10 mg/ml; swirl gently, do not shake." },
      { label: "Saklama", value: "refrigerate 2 – 8 °C after mixing; freeze-dried powder is room-temperature stable during shipping." },
      { label: "Örnek Araştırma Dozu", value: "100–200 µg of each peptide (0.02–0.04 ml) sub-Q 3 × daily pre-meal or pre-workout for 4–6 weeks." },
    ],
    notes: [
      "Mega Mass Mix — growth-hormone & appetite amplifier",
      "5 lyophilised vials × 10 mg (total 50 mg)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; scratch-code authenticity on every box.",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "melanotan-2-10mg-bacteriostatic-water-zphc",
    name: "Melanotan-2 ZPHC — 10 mg (1 lyophilized vial)",
    sku: "MEL10-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2024/06/melanotan-2.jpg",
    sourcePriceUsd: 20.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Melanotan-2" },
      { label: "Konsantrasyon", value: "10 mg per vial" },
      { label: "Hacim", value: "1 vial + Bacteriostatic Water" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Skin tanning, photoprotection, and potential appetite suppression" },
      { label: "Etki", value: "Melanotan-2 stimulates the production of melanin in the body, resulting in a deep, natural tan without the need for prolonged exposure to UV rays. It also provides some protection against UV radiation and may reduce appetite." },
      { label: "Uygulama Yolu", value: "Subcutaneous injections after reconstitution" },
      { label: "Önerilen Doz", value: "Prescribed by a healthcare professional, typically starting with a low dose and gradually increasing" },
      { label: "Yan Etkiler", value: "Possible side effects include nausea, flushing, increased libido, and potential darkening of moles or freckles" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "melanotan-2-30mg-aq-pen-zphc",
    name: "Melanotan-II (AQ Pen) ZPHC — 30 mg Premixed",
    sku: "MT2AQ30-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/mt2-30mg-aq-pen-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Kullanıma Hazır", value: "water-based MT-2 comes pre-dissolved — no vials, no reconstitution, no syringes." },
      { label: "Dial-a-dose", value: "each click delivers 150 µg; 10 clicks = 1.5 mg. Graduated window shows remaining volume." },
      { label: "Suggested research schedule", value: "250 µg (≈ 2 clicks) daily for 5 days → 500 µg maintenance twice weekly until desired tone." },
      { label: "Saklama", value: "ship cold; refrigerate 2 – 8 °C once opened, stable 30 days." },
    ],
    notes: [
      "Melanotan-II (MT-2) — Premixed Aqueous Pen",
      "30 mg total • 200 × 150 µg clicks",
      "Rapid tanning & photo-protection: stimulates α-MSH receptors → darker base pigment & reduced UV damage.",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; pen sterilised & tamper-evident.",
    ],
  },
  {
    slug: "multi-use-pen-36iu-cartridges-zphc",
    name: "Multi-Use Pen ZPHC (For 36 IU Cartridges)",
    sku: "PEN-MU-ZPHC",
    category: "aksesuar",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/multi-use-pen-for-36-iu-zphc-1.jpg",
    sourcePriceUsd: 30.0,
    specs: [
      { label: "Compatibility", value: "designed for use with ZPTROP 36 IU single-chamber cartridges." },
      { label: "Device type", value: "reusable precision dosing pen (non-clinical device)." },
      { label: "Function", value: "adjustable IU dosing mechanism for controlled administration." },
      { label: "Design", value: "durable aluminum body with clear dose-display window." },
      { label: "Application", value: "intended for research use only; not for diagnostic or therapeutic applications." },
      { label: "Model", value: "ZP-MU36V1." },
    ],
    notes: [
      "ZPHC Multi-Use Pen — Reusable Dosing Device",
      "Compatible with 36 IU Cartridges",
    ],
  },
  {
    slug: "nad-plus-2500mg-zphc",
    name: "NAD+ ZPHC — 2500 mg KIT (5 vials × 500 mg)",
    sku: "NAD2500-ZPHC",
    category: "peptid",
    peptideSlug: "nad-nmn",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/NAD-2500MG-KIT-5VIAL-ZPHC-1.jpg",
    sourcePriceUsd: 139.0,
    specs: [
      { label: "Cellular energy support", value: "essential cofactor for ATP production, mitochondrial efficiency and overall metabolic function." },
      { label: "Longevity pathways", value: "involved in sirtuin activation (SIRT1–7), DNA-repair mechanisms and healthy-aging research models." },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥ 98.9% purity (HPLC); manufactured under GMP & ISO 17034:2016 with ZPHC scratch-code verification." },
      { label: "Rekonstitüsyon", value: "combine with sterile diluent provided; swirl gently until fully dissolved. Store at 2–8 °C." },
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for therapeutic use." },
    ],
    notes: [
      "NAD+ (Nicotinamide Adenine Dinucleotide) — ZPHC Pro-Line",
      "5 lyophilised vials × 500 mg (total 2500 mg) + sterile diluent",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "reta-60mg-dual-cartridge-sterile-water-zphc",
    name: "Reta 60mg PEN ZPHC - (Dual-Chamber Cartridge + Sterile Water)",
    sku: "RET60PEN-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/reta-60mg-pen-dual-cartrige-zphc-1.jpg",
    sourcePriceUsd: 359.0,
    specs: [
      { label: "Dual-chamber cartridge (60mg)", value: "contains 60mg lyophilized powder in one chamber and sterile water for injection in the second chamber; components remain separated until activation, mixing occurs immediately prior to use." },
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-30mg-aq-pen-zphc",
    name: "Reta ZPHC (AQ pen) — 30 mg Premixed Pen",
    sku: "RET30B-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta30mg.jpg",
    sourcePriceUsd: 219.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-10mg-5x2mg-zphc-2",
    name: "Reta ZPHC — 10 mg (5 vials × 2 mg)",
    sku: "RET10-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta10mg.jpg",
    sourcePriceUsd: 83.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "reta-zphc-120-mg-5-vials-x-24-mg",
    name: "Reta ZPHC — 120 mg (5 vials × 24 mg)",
    sku: "RET120-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/reta120mg.jpg",
    sourcePriceUsd: 589.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-zphc-15-mg-1vial",
    name: "Reta ZPHC — 15 mg (15 mg * 1 vial)",
    sku: "RET15-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/reta15mg.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-20mg-5x4mg-zphc",
    name: "Reta ZPHC — 20 mg (5 vials × 4 mg)",
    sku: "RET20-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta20mg.jpg",
    sourcePriceUsd: 138.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-40mg-5x8mg-zphc",
    name: "Reta ZPHC — 40 mg (5 vials × 8 mg)",
    sku: "RET40-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta40mg.jpg",
    sourcePriceUsd: 239.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-60mg-5x12mg-zphc",
    name: "Reta ZPHC — 60 mg (5 vials × 12 mg)",
    sku: "RET60-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta60mg.jpg",
    sourcePriceUsd: 339.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "spectros-140iu-hgh-spectrum-pharma",
    name: "SPECTROS 140IU HGH Spectrum Pharma",
    sku: "HGH140-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-140iu-SpectrumPharma.jpg",
    sourcePriceUsd: 239.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "14 IU per vial (140 IU)" },
      { label: "Hacim", value: "10 vials, each with 14 IU" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Growth hormone therapy, muscle mass enhancement, fat reduction, and anti-aging" },
      { label: "Etki", value: "Stimulates growth, promotes fat burning, increases lean muscle mass, improves recovery, and enhances overall vitality" },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injections after reconstitution" },
      { label: "Önerilen Doz", value: "Typically 2-4 IU per day, as prescribed by a healthcare professional" },
      { label: "Yan Etkiler", value: "Possible side effects include joint pain, water retention, carpal tunnel syndrome, and increased blood sugar levels" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "spectros-150iu-hgh-spectrum-pharma",
    name: "SPECTROS 150IU HGH Spectrum Pharma",
    sku: "HGH150-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-150iu-SpectrumPharma.jpg",
    sourcePriceUsd: 229.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "150 IU per vial" },
      { label: "Hacim", value: "1 vial, each with 150 IU" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Muscle growth, fat loss, anti-aging, improved recovery, enhanced athletic performance" },
      { label: "Etki", value: "Stimulates growth, promotes fat burning, increases lean muscle mass, improves recovery, and enhances overall vitality" },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injections after reconstitution" },
      { label: "Önerilen Doz", value: "Dosage varies based on individual goals; typically 2-4 IU per day, as prescribed by a healthcare professional" },
      { label: "Yan Etkiler", value: "Possible side effects include joint pain, water retention, carpal tunnel syndrome, and increased blood sugar levels" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "spectros-280iu-hgh-spectrum-pharma",
    name: "SPECTROS 280iu HGH Spectrum Pharma",
    sku: "HGH280-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-280iu-SpectrumPharma.jpg",
    sourcePriceUsd: 399.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "28 IU per vial (280 IU)" },
      { label: "Hacim", value: "10 vials, each with 28 IU" },
      { label: "Form", value: "Lyophilized powder for reconstitution" },
      { label: "Kullanım Amacı", value: "Muscle growth, fat loss, anti-aging, improved recovery, enhanced athletic performance" },
      { label: "Etki", value: "Stimulates growth, promotes fat burning, increases lean muscle mass, improves recovery, and enhances overall vitality" },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injections after reconstitution" },
      { label: "Önerilen Doz", value: "Dosage varies based on individual goals; typically 2-4 IU per day, as prescribed by a healthcare professional" },
      { label: "Yan Etkiler", value: "Possible joint pain, swelling, insulin resistance, and carpal tunnel syndrome" },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light, and refrigerate after reconstitution" },
    ],
    notes: [],
  },
  {
    slug: "semaglutide-10mg-5x2mg-zphc",
    name: "Semaglutide ZPHC — 10 mg (5 vials × 2 mg)",
    sku: "SEM10-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Semaglutide-10mg-ZPHC-2.jpg",
    sourcePriceUsd: 76.0,
    specs: [
      { label: "Araştırma Odağı", value: "appetite suppression, delayed gastric emptying, improved insulin sensitivity and rapid fat-loss." },
      { label: "Haftada Tek Doz Protokolü", value: "long half-life allows a single sub-Q dose per week." },
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 2 mg / ml; swirl gently, avoid foaming. Store 2 – 8 °C." },
      { label: "Titration guide (research)", value: "Week 1-4 → 0.25 mg • Week 5-8 → 0.5 mg • escalate to 1 mg weekly if well-tolerated." },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥ 99 % purity, endotoxin < 0.03 EU / mg; each box bears a scratch-code for authenticity." },
    ],
    notes: [
      "Semaglutide — GLP-1 receptor agonist",
      "5 lyophilised vials × 2 mg (total 10 mg)",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "semaglutide-20mg-5x4mg-zphc",
    name: "Semaglutide ZPHC — 20 mg (5 vials × 4 mg)",
    sku: "SEM20-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Semaglutide-20mg-ZPHC-5.jpg",
    sourcePriceUsd: 143.0,
    specs: [
      { label: "Araştırma Odağı", value: "powerful appetite suppression, delayed gastric emptying, improved insulin sensitivity and rapid fat-loss." },
      { label: "Haftada Tek Doz Protokolü", value: "long half-life allows a single sub-Q injection per week." },
      { label: "Rekonstitüsyon", value: "add 2 ml bacteriostatic water → 2 mg/ml; swirl gently, avoid foaming. Store 2 – 8 °C." },
      { label: "Titration guide (research)", value: "Week 1-4 → 0.25 mg • Week 5-8 → 0.5 mg • escalate to 1 mg weekly if well-tolerated." },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥ 99 % purity, endotoxin < 0.03 EU/mg; each box bears a scratch-code for authenticity." },
    ],
    notes: [
      "Semaglutide — GLP-1 receptor agonist",
      "5 lyophilised vials × 4 mg (total 20 mg)",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "semaglutide-5mg-kit-zphc",
    name: "Semaglutide ZPHC — 5 mg (5 vials × 1 mg)",
    sku: "SEM5-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2024/02/semaglutide-zphc.jpg",
    sourcePriceUsd: 44.0,
    specs: [
      { label: "Next-gen GLP-1 agonist", value: "clinically shown to curb appetite, improve glycaemic control and drive sustainable fat-loss." },
      { label: "Weekly dosing convenience", value: "long half-life allows once-weekly sub-Q injections." },
      { label: "Simple reconstitution", value: "add 1 ml bacteriostatic water to each vial → 1 mg/ml solution (0.1 ml = 0.1 mg). Refrigerate 2 – 8 °C." },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free; scratch-code authenticity on every box." },
    ],
    notes: [
      "Semaglutide – 5 lyophilized vials × 1 mg (total 5 mg)",
      "Dose guide (research): 0.25 mg once weekly × 4 wk → 0.5 mg × 4 wk → 1 mg maintenance; escalate only if well-tolerated.",
      "Cold-chain packed • tamper-evident packaging • discreet, tracked worldwide shipping.",
    ],
  },
  {
    slug: "semaglutide-zphc-50-mg-5-vials-x-10-mg",
    name: "Semaglutide ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "SEM50-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/SEMAGLUTIDE-50MG-KIT-ZPHC-2.jpg",
    sourcePriceUsd: 279.0,
    specs: [
      { label: "Araştırma Odağı", value: "powerful appetite suppression, delayed gastric emptying, improved insulin sensitivity and rapid fat-loss." },
      { label: "Haftada Tek Doz Protokolü", value: "long half-life allows a single sub-Q injection per week." },
      { label: "Rekonstitüsyon", value: "add 2 ml bacteriostatic water → 2 mg/ml; swirl gently, avoid foaming. Store 2 – 8 °C." },
      { label: "Titration guide (research)", value: "Week 1-4 → 0.25 mg • Week 5-8 → 0.5 mg • escalate to 1 mg weekly if well-tolerated." },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥ 99 % purity, endotoxin < 0.03 EU/mg; each box bears a scratch-code for authenticity." },
    ],
    notes: [
      "Semaglutide — GLP-1 receptor agonist",
      "5 lyophilised vials × 10 mg (total 50 mg)",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "semaglutide-6mg-aq-pen-zphc",
    name: "Semaglutide ZPHC — 6 mg Premixed Pen",
    sku: "SEM6-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/SEMAGLUTIDE-6mg-pen-4.jpg",
    sourcePriceUsd: 105.0,
    specs: [
      { label: "No mixing required", value: "fully dissolved peptide — simply dial the dose and inject sub-Q." },
      { label: "Metabolic action", value: "slows gastric emptying, suppresses appetite and improves insulin sensitivity." },
      { label: "Dial-a-dose precision", value: "each click delivers 0.25 mg; the pen provides 24 clicks (6 mg total)." },
      { label: "Suggested research titration", value: "0.25 mg weekly → increase by 0.25 mg every 4 weeks up to 1 mg, as tolerated." },
      { label: "Saklama", value: "ship on ice; refrigerate 2 – 8 °C after opening; solution stable 28 days when kept cold." },
    ],
    notes: [
      "Semaglutide — GLP-1 receptor agonist",
      "6 mg pre-filled aqueous pen • 24 clicks × 0.25 mg",
      "QC: ≥ 99 % purity, endotoxin < 0.03 EU/mg; pen sterilised and tamper-evident with scratch-code authenticity.",
    ],
  },
  {
    slug: "super-slim-mix-275mg-5x55mg-zphc",
    name: "Super Slim Mix ZPHC — 27,5 mg (5 vials × 5,5 mg)",
    sku: "SUP275-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Super-slim-mix-5.5mg-vial-27.5mg-kit-ZPHC-1.jpg",
    sourcePriceUsd: 149.0,
    specs: [
      { label: "Rekonstitüsyon", value: "add 1 ml bacteriostatic water → 5.5 mg/ml. Store 2 – 8 °C." },
      { label: "Örnek Araştırma Dozu", value: "0.25 – 0.5 ml sub-Q daily (≈ 1.4 – 2.8 mg) for 4 – 6 weeks." },
    ],
    notes: [
      "Super Slim Mix — triple-pathway fat-loss blend",
      "5 lyophilised vials × 5.5 mg (total 27.5 mg)",
      "AOD 9604 2.5 mg: HGH fragment that enhances lipolysis and blocks lipogenesis.",
      "FRAG 176-191 2.5 mg: targets adipose tissue for selective fat reduction.",
      "Adipotide 0.5 mg: induces adipocyte apoptosis by disrupting blood supply.",
      "QC: ≥ 99 % purity, endotoxin < 0.03 EU/mg, box with scratch-code authenticity.",
    ],
  },
  {
    slug: "super-slim-mix-55mg-5x11mg-zphc",
    name: "Super Slim Mix ZPHC — 55 mg (5 vials × 11 mg)",
    sku: "SUP55-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Super-slim-mix-11mg-55mg-kit-ZPHC-4.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Flakon Başına Formül", value: "AOD 9604 5 mg · FRAG 176-191 5 mg · Adipotide 1 mg." },
      { label: "Synergistic action", value: "AOD & FRAG accelerate lipolysis; Adipotide selectively reduces fat cell vascularisation." },
      { label: "Rekonstitüsyon", value: "add 2 ml bacteriostatic water → 5.5 mg/ml. Swirl gently; refrigerate 2–8 °C." },
      { label: "Örnek Araştırma Dozu", value: "0.25 ml (≈ 1.4 mg) to 0.5 ml (≈ 2.8 mg) sub-Q daily for 4–6 weeks." },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥ 99 % purity, endotoxin < 0.03 EU/mg; scratch-code authenticity on every box." },
    ],
    notes: [
      "Super Slim Mix — triple-pathway fat-loss blend",
      "5 lyophilised vials × 11 mg (total 55 mg)",
      "Cold-chain packed · tamper-evident vial · discreet, tracked worldwide delivery.",
    ],
  },
  {
    slug: "zphc-tb500-20mg-with-bacteriostatic-water",
    name: "TB-500 20mg Kit (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "TB50020-ZPHC",
    category: "peptid",
    peptideSlug: "tb-500",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/Tb-500-20mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 109.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 20mg lyophilized TB-500 (powder) + 1 vial bacteriostatic water for reconstitution." },
      { label: "Peptid Profili", value: "TB-500 (Thymosin Beta-4 fragment), high-purity laboratory-grade material." },
      { label: "Rekonstitüsyon", value: "add supplied bacteriostatic water under sterile conditions; swirl gently until fully dissolved." },
      { label: "Araştırma Alanları", value: "tissue-repair models, angiogenesis studies, recovery and regeneration pathways, cellular migration research." },
      { label: "Taşıma ve Muhafaza", value: "refrigerate after reconstitution at 2–8 °C; avoid freezing; store lyophilized powder in a cool, dry place." },
      { label: "Kalite Kontrolü", value: "batch-tracked, hermetically sealed sterile glass vials; for research use only." },
    ],
    notes: [
      "TB-500 20mg — Thymosin Beta-4 Fragment",
      "Lyophilized Peptide + Bacteriostatic Water",
    ],
  },
  {
    slug: "tb500-25mg-5x5mg-zphc",
    name: "TB-500 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "TB50025-ZPHC",
    category: "peptid",
    peptideSlug: "tb-500",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Tb-500-25mg-Kit-ZPHC-8.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Anti-inflammatory action", value: "helps reduce swelling and post-injury stiffness." },
      { label: "Doz Rehberi", value: "2–5 mg weekly (split into 2–3 shots) for 4–6 weeks, then 2 mg every 10–14 days to maintain." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free, scratch-code authenticity." },
    ],
    notes: [
      "Pharma-grade TB-500 (Thymosin β-4 fragment) – 5 vials × 5 mg (total 25 mg)",
      "Tissue & joint repair: accelerates healing of muscles, tendons, ligaments and skin.",
      "Pure 5 mg lyophilized vials: reconstitute with 2–3 ml bacteriostatic water for clear solution.",
      "Temperature-controlled shipping • discreet packaging • tracked worldwide delivery.",
    ],
  },
  {
    slug: "tirze-zphc-75-mg-dual-cartridge-pen",
    name: "Tirze 75mg Dual Cartridge Pen",
    sku: "TIR75-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/t-75mg.jpg",
    sourcePriceUsd: 339.0,
    specs: [
      { label: "Dual-chamber cartridge (75mg)", value: "contains 75mg lyophilized powder in one chamber and sterile water for injection in the second chamber; components remain separated until activation, mixing occurs immediately prior to use." },
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-zphc-150-mg-5-vials-x-30-mg",
    name: "Tirze ZPHC — 150 mg (5 vials × 30 mg)",
    sku: "TIRZEP150-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/tirzepatide-150mg-zphc.jpg",
    sourcePriceUsd: 699.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-30mg-aq-pen-zphc",
    name: "Tirze ZPHC — 30 mg Premixed Pen",
    sku: "TIR30-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/terzipatide-pen-30mg-zphc.jpg",
    sourcePriceUsd: 189.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-37p5mg-5x7p5mg-zphc",
    name: "Tirze ZPHC — 37.5 mg (5 vials × 7.5 mg)",
    sku: "TIRZEP75-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/terzipatide-37-5-zphc.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-50mg-5x10mg-zphc",
    name: "Tirze ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "TIRZEP10-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/tirzepatide-50mg-zphc.jpg",
    sourcePriceUsd: 259.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "analytical reference material; not intended for human use." },
    ],
    notes: [],
  },
  {
    slug: "zphc-ultra-rehab-mix-20mg-bpc157-tb500",
    name: "Ultra Rehab Mix ZPHC - 20mg (BPC-157 + TB-500)",
    sku: "URMIX25-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/ultra-rehab-20mg-kit-zphc-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Composition", value: "dual peptide blend containing 10mg BPC-157 and 10mg TB-500 (Thymosin Beta-4 fragment)." },
      { label: "Toplam İçerik", value: "20mg per vial; hermetically sealed sterile glass container." },
      { label: "Rekonstitüsyon", value: "add bacteriostatic water under sterile conditions; swirl gently until fully dissolved." },
      { label: "Araştırma Alanları", value: "tissue-repair models, tendon/ligament regeneration studies, inflammation-response pathways, recovery-focused laboratory protocols." },
      { label: "Sample research protocols", value: "dosing varies depending on study design and analytical framework." },
      { label: "Saklama", value: "keep lyophilized powder cool and dry; refrigerate reconstituted solution at 2–8 °C; avoid freezing." },
      { label: "Kalite Kontrolü", value: "high-purity peptides, batch-tracked and authenticity verified; for research use only." },
    ],
    notes: [
      "Ultra Rehab Mix 20mg — BPC-157 + TB-500",
      "10mg BPC-157 + 10mg TB-500 | Research Peptide Kit",
    ],
  },
  {
    slug: "ultra-rehab-mix-50mg-5x10mg-zphc",
    name: "Ultra Rehab Mix ZPHC — 50 mg (BPC-157 5 mg + TB-500 5 mg) — 5 vials × 10 mg",
    sku: "URMIX50-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Ultra-Rehab-50mg-Kit-ZPHC-3.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Liyofilize Saflık", value: "reconstitute each 10 mg vial with 2 ml bacteriostatic water to yield 5 mg/ml total peptide (2.5 mg BPC + 2.5 mg TB per ml)." },
      { label: "Doz Rehberi", value: "2–5 mg (1–2 ml) weekly, split over 2–3 sub-Q injections for 4–6 weeks, then 2 mg every 10–14 days to maintain." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free; tamper-evident box with scratch-code authenticity." },
    ],
    notes: [
      "Ultra Rehab Mix – dual-peptide healing stack (5 vials × 10 mg, total 50 mg)",
      "BPC-157 5 mg + TB-500 5 mg in every vial – synergistic combo for faster tendon, ligament and muscle repair.",
      "Anti-inflammatory & protective: helps reduce swelling, boosts collagen deposition and blood-flow to injured tissue.",
      "Insulated worldwide shipping • discreet packaging • multilingual support.",
    ],
  },
  {
    slug: "wellness-mix-25mg-5x5mg-zphc",
    name: "Wellness Mix ZPHC — 25 mg (Ipamorelin 2.5 mg + CJC-1295 2.5 mg) — 5 vials × 5 mg",
    sku: "WMIX25-ZPHC",
    category: "peptid",
    peptideSlug: "ipamorelin",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Wellness-Mix-25mg-Kit-ZPHC-5.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Dual action", value: "Ipamorelin 2.5 mg + CJC-1295 2.5 mg amplify natural GH & IGF-1 release." },
      { label: "Benefits", value: "lean-muscle retention, fat oxidation, deeper sleep and faster recovery." },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC batches ≥ 99 % purity, endotoxin-free, micro-filtered." },
      { label: "Doz Rehberi", value: "1 vial reconstituted = 5 mg; inject 300–500 mcg daily, 6–8 weeks." },
    ],
    notes: [
      "Wellness Mix – synergistic peptide combo (5 vials × 5 mg)",
      "Sealed vials in tamper-evident box • scratch-code authenticity • tracked worldwide shipping.",
    ],
  },
  {
    slug: "zphc-nad-plus-1000mg-with-bacteriostatic-water",
    name: "ZPHC NAD+ 1000mg Kit (Lyophilized Powder + Bacteriostatic Water)",
    sku: "NAD1000-ZPHC",
    category: "peptid",
    peptideSlug: "nad-nmn",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/NAD-1000MG-KIT-ZPHC-1.jpg",
    sourcePriceUsd: 63.0,
    specs: [
      { label: "Kit İçeriği", value: "1 vial 1000mg lyophilized NAD+ + 1 vial bacteriostatic water for reconstitution." },
      { label: "Compound profile", value: "β-Nicotinamide Adenine Dinucleotide (oxidized form), high-purity laboratory-grade material." },
      { label: "Rekonstitüsyon", value: "add supplied bacteriostatic water under sterile conditions; gently swirl until fully dissolved." },
      { label: "Araştırma Alanları", value: "cellular energy metabolism studies, mitochondrial function models, longevity pathways, NAD+ restoration research." },
      { label: "Taşıma ve Muhafaza", value: "refrigerate after reconstitution at 2–8 °C; protect from light; store lyophilized powder in a cool, dry place." },
      { label: "Kalite Kontrolü", value: "batch-verified, hermetically sealed sterile vials; for research use only." },
    ],
    notes: [
      "NAD+ 1000mg — Nicotinamide Adenine Dinucleotide",
      "Lyophilized Powder + Bacteriostatic Water",
    ],
  },
  {
    slug: "zptrop-144iu-2x72iu-two-chamber-cartridges-zphc",
    name: "ZPTROP 144 IU Kit ZPHC (2×72 IU Two-Chamber Cartridges)",
    sku: "HGH144-AQ-CART-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/zptrop-144iu-two-chamber-cartriges-zphc-2.jpg",
    sourcePriceUsd: 229.0,
    specs: [
      { label: "Format", value: "2 hermetically sealed dual-chamber glass cartridges." },
      { label: "Content per cartridge", value: "72 IU (24mg) Somatropin 191aa (rDNA origin)." },
      { label: "Two-chamber system", value: "lyophilized peptide and sterile diluent remain separated until activation and mixing." },
      { label: "Total kit", value: "144 IU." },
      { label: "Compatibility", value: "designed for use with compatible multi-use pen devices." },
      { label: "Kalite Kontrolü", value: "certified reference material (CRM), batch-verified and authenticity-protected." },
      { label: "Notice", value: "for professional use only." },
    ],
    notes: [
      "ZPTROP 144 IU — Two-Chamber Somatropin Cartridges",
      "2 × 72 IU (24mg) Dual-Chamber System",
    ],
  },
  {
    slug: "zphc-zptrop-72iu-dual-chamber-pen",
    name: "ZPTROP 72 IU ZPHC Dual-Chamber Pen (24mg)",
    sku: "ZPTAQ72-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/Zptrop-AQ-72IU-pen-ZPHC-2.jpg",
    sourcePriceUsd: 159.0,
    specs: [
      { label: "Format", value: "sterile dual-chamber pen with separated compartments." },
      { label: "Content", value: "24mg (72 IU) lyophilized Somatropin 191aa (rDNA origin) + sterile diluent." },
      { label: "Activation system", value: "powder and diluent remain separated until activation; automatic mixing occurs prior to first use." },
      { label: "Delivery", value: "precision IU-adjustable dosing mechanism." },
      { label: "Kalite Kontrolü", value: "hermetically sealed system, batch-verified and authenticity-protected." },
      { label: "Notice", value: "certified reference material (CRM); for professional use only." },
    ],
    notes: [
      "ZPTROP 72 IU — Dual-Chamber Pen System",
      "24mg (72 IU) Somatropin",
    ],
  },
  {
    slug: "zptrop-hgh-36iu-aq-pen-zphc",
    name: "ZPtrop HGH (AQ pen) ZPHC — 36 IU Premixed Pen",
    sku: "ZPTAQ36-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Zptrop-AQ-36IU-pen-ZPHC-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Kullanıma Hazır", value: "fully dissolved somatropin solution — no vials or bacteriostatic water needed." },
      { label: "Micro-precision dial", value: "each click delivers ~0.6 IU (0.2 mg). 60 clicks = full 36 IU." },
      { label: "Araştırma Alanları", value: "lean tissue repair, fat-loss, sleep quality, collagen synthesis & anti-aging models." },
      { label: "Suggested research dosing", value: "2–4 IU pre-bed for recovery/anti-aging • 4–6 IU split AM/PM for fat-loss • 8–10 IU for hypertrophy protocols." },
      { label: "Saklama", value: "ship on ice; refrigerate 2 – 8 °C once opened. Stable 28 days at 2–8 °C." },
    ],
    notes: [
      "ZPtrop Human Growth Hormone — 191-aa rhGH",
      "36 IU pre-filled aqueous pen • 60 clicks × 0.6 IU",
      "QC: ≥ 99 % purity (HPLC), endotoxin < 0.03 EU/mg; sterile, tamper-evident pen with scratch-code authenticity.",
    ],
  },
  {
    slug: "zptropin-hgh-320iu-zphc",
    name: "ZPtrop HGH 320iu ZPHC",
    sku: "HGH320-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2023/07/zptrop-320-1.jpg",
    sourcePriceUsd: 449.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "32 IU (10.6 mg) per vial" },
      { label: "Hacim", value: "10 vials" },
      { label: "Form", value: "Lyophilized powder for reconstitution with Bacteriostatic Water" },
      { label: "Kullanım Amacı", value: "Growth hormone therapy, muscle mass gain, fat loss, anti-aging" },
      { label: "Etki", value: "Promotes growth hormone therapy benefits, including increased muscle mass, reduced body fat, enhanced recovery, and anti-aging effects. It is commonly used by athletes and bodybuilders to improve physical performance and body composition." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injection after reconstitution" },
      { label: "Önerilen Doz", value: "Typically administered at doses prescribed by a healthcare professional, often ranging from 2-10 IU per day." },
      { label: "Yan Etkiler", value: "Include joint pain, water retention, insulin resistance, and potential increased risk of diabetes. Regular monitoring and consultation with a healthcare provider are advised." },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution." },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-80iu-zphc-bacteriostatic-water",
    name: "ZPtrop HGH 80iu ZPHC + Bacteriostatic Water",
    sku: "HGH80-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2023/07/zptrop-80-1.jpg",
    sourcePriceUsd: 179.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "5 vials" },
      { label: "Hacim", value: "5 vials, Includes Bacteriostatic Water for reconstitution" },
      { label: "Form", value: "Lyophilized powder for reconstitution with Bacteriostatic Water" },
      { label: "Kullanım Amacı", value: "Growth hormone therapy, muscle mass gain, fat loss, anti-aging" },
      { label: "Etki", value: "Promotes muscle growth, reduces body fat, enhances recovery, and has anti-aging effects." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injection after reconstitution" },
      { label: "Önerilen Doz", value: "Typically 2-10 IU per day, as prescribed by a healthcare professional." },
      { label: "Yan Etkiler", value: "Possible side effects include joint pain, water retention, insulin resistance, and potential increased risk of diabetes." },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution." },
    ],
    notes: [],
  },
  {
    slug: "zptrop-100iu-zphc",
    name: "ZPtrop HGH ZPHC — 100 IU (1 lyophilized vial)",
    sku: "HGH100-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/10/zptrop-hgh-100iu-1.jpg",
    sourcePriceUsd: 189.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "100iu" },
      { label: "Hacim", value: "1 vial" },
      { label: "Form", value: "Lyophilized powder for reconstitution with Bacteriostatic Water" },
      { label: "Kullanım Amacı", value: "Growth hormone therapy, muscle mass gain, fat loss, anti-aging" },
      { label: "Etki", value: "Promotes muscle growth, reduces body fat, enhances recovery, and has anti-aging effects." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injection after reconstitution" },
      { label: "Önerilen Doz", value: "Typically 2-10 IU per day, as prescribed by a healthcare professional." },
      { label: "Yan Etkiler", value: "Possible side effects include joint pain, water retention, insulin resistance, and potential increased risk of diabetes." },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution." },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-100iu-aq-vial-zphc",
    name: "ZPtrop HGH ZPHC — 100 IU Premixed Vial",
    sku: "ZPTAQ100-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Zptrop-100-aq-ZPHC-4.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "No reconstitution", value: "fully dissolved somatropin solution — simply draw the desired IU with an insulin syringe." },
      { label: "Graduated stopper", value: "3 IU (≈ 1 mg) increments marked on label for precise dosing; 33 full draws per vial." },
      { label: "Araştırma Alanları", value: "lean-tissue repair, lipolysis, collagen synthesis, deeper sleep & anti-aging models." },
      { label: "Örnek Araştırma Dozu", value: "2–4 IU pre-bed (recovery/anti-aging) • 4–6 IU split AM/PM (fat-loss) • 8–10 IU/day (hypertrophy)." },
      { label: "Saklama", value: "ship on ice; refrigerate 2–8 °C after opening; stable 28 days when kept cold." },
    ],
    notes: [
      "ZPtrop Human Growth Hormone — 191-aa rhGH",
      "100 IU premixed aqueous vial • 33.3 mg total (multi-dose)",
      "QC: ≥ 99 % purity (HPLC); endotoxin < 0.03 EU/mg; every vial bears a scratch-code for authenticity.",
    ],
  },
  {
    slug: "zptrop-16iu-1vial-zphc",
    name: "ZPtrop HGH ZPHC — 16 IU (1 lyophilized vial + bac water)",
    sku: "HGH16-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-16IU-1vial-1Bwater-ZPHC-4.jpg",
    sourcePriceUsd: 34.0,
    specs: [
      { label: "Standard reconstitution", value: "add supplied bac water; swirl gently until the somatropin fully dissolves into a clear solution." },
      { label: "Konsantrasyon", value: "16 IU per vial (≈ 5.3 mg total) after reconstitution; suitable for insulin syringes and micro-dosing." },
      { label: "Araştırma Alanları", value: "lean-tissue repair, fat-metabolism models, collagen synthesis, recovery, sleep & anti-aging studies." },
      { label: "Örnek Araştırma Dozu", value: "1–2 IU daily (well-being/repair) • 2–3 IU (fat-loss models) • 3–4 IU (hypertrophy protocols)." },
      { label: "Saklama", value: "keep powder cool and dry; refrigerate reconstituted solution at 2–8 °C; stable 7–10 days after mixing." },
    ],
    notes: [
      "ZPtrop Human Growth Hormone — 191-aa rhGH",
      "16 IU lyophilized vial + 1× bacteriostatic water",
      "QC: ≥ 98–99% purity (HPLC); low endotoxin profile; each vial batch-verified for authenticity and consistency.",
    ],
  },
  {
    slug: "zptrop-hgh-160iu-zphc",
    name: "ZPtrop HGH ZPHC — 160 IU (16 vials × 10 IU)",
    sku: "HGH160-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2019/03/zptrop-160-1.jpg",
    sourcePriceUsd: 279.0,
    specs: [
      { label: "Üretici", value: "ZPHC" },
      { label: "Etkin Madde", value: "Somatropin" },
      { label: "Konsantrasyon", value: "16 IU (5.3 mg) per vial" },
      { label: "Hacim", value: "10 vials" },
      { label: "Form", value: "Lyophilized powder for reconstitution with Bacteriostatic Water" },
      { label: "Kullanım Amacı", value: "Growth hormone therapy, muscle mass gain, fat loss, anti-aging" },
      { label: "Etki", value: "Promotes growth hormone therapy benefits, including increased muscle mass, reduced body fat, enhanced recovery, and anti-aging effects." },
      { label: "Uygulama Yolu", value: "Subcutaneous or intramuscular injection after reconstitution" },
      { label: "Önerilen Doz", value: "Typically administered at doses prescribed by a healthcare professional, often ranging from 2-10 IU per day." },
      { label: "Yan Etkiler", value: "Include joint pain, water retention, insulin resistance, and potential increased risk of diabetes." },
      { label: "Saklama", value: "Store in a cool, dry place, protected from light. Refrigerate after reconstitution." },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-200iu-2x100iu-zphc",
    name: "ZPtrop HGH ZPHC — 200 IU (2 vials × 100 IU)",
    sku: "HGH200-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/01/zptrop-200iu-zphc-2-1.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Doz Rehberi", value: "2–4 IU daily for wellness/cutting, 4–6 IU for muscle gain." },
      { label: "Cold-chain handled", value: "shipped 2 – 8 °C in insulated packaging with temperature indicator." },
      { label: "Batch-tested quality", value: "ZPHC QC ≥ 99 % purity, endotoxin-free; scratch code for authenticity." },
    ],
    notes: [
      "Pharma-grade ZPtrop HGH (191-aa somatropin) – 2 vials × 100 IU",
      "Lean-muscle & fat-loss synergy: boosts IGF-1, speeds recovery and improves sleep quality.",
      "Pure 100 IU vials: lyophilized powder reconstitutes clear; bacteriostatic water included.",
      "Discreet worldwide shipping • multilingual support • secure checkout.",
    ],
  },
  {
    slug: "zptrop-32iu-1vial-zphc",
    name: "ZPtrop HGH ZPHC — 32 IU (1 lyophilized vial + bac water)",
    sku: "HGH32-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-32IU-1vial-1Bwater-ZPHC-2.jpg",
    sourcePriceUsd: 65.0,
    specs: [
      { label: "Standard reconstitution", value: "add supplied bac water; swirl gently to obtain a clear somatropin solution." },
      { label: "Konsantrasyon", value: "32 IU per vial (≈ 10.7 mg total) after reconstitution; compatible with insulin syringes." },
      { label: "Araştırma Alanları", value: "lean-tissue repair, fat-metabolism models, collagen synthesis, sleep optimization, anti-aging pathways." },
      { label: "Örnek Araştırma Dozu", value: "2–4 IU daily (well-being/repair) • 4–6 IU (fat-loss models) • 6–8 IU (muscle-hypertrophy protocols)." },
      { label: "Saklama", value: "keep powder cool and dry; refrigerate reconstituted solution at 2–8 °C; stable 10–14 days after mixing." },
    ],
    notes: [
      "ZPtrop Human Growth Hormone — 191-aa rhGH",
      "32 IU lyophilized vial + 1× bacteriostatic water",
      "QC: ≥ 98–99% purity (HPLC); low endotoxin; each vial verified and batch-tracked for authenticity.",
    ],
  },
  {
    slug: "zptrop-150-aq-zphc-premixed",
    name: "Zptrop 150 AQ ZPHC - Premixed",
    sku: "HGH150-AQ-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-150IU-AQ-15IU-10VIAL-ZPHC-7.jpg",
    sourcePriceUsd: 237.0,
    specs: [
      { label: "Ready-to-use HGH", value: "fully premixed recombinant human growth hormone in sterile aqueous solution for consistent potency." },
      { label: "Somatotropic support", value: "researched for muscle repair, improved recovery, fat-metabolism enhancement and performance optimisation." },
      { label: "No reconstitution required", value: "each vial contains a pre-dissolved, uniform 15 IU dose for immediate use." },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥ 99% purity (HPLC); produced under GMP & ISO standards with ZPHC scratch-code verification." },
      { label: "Saklama", value: "refrigerate at 2–8 °C; avoid freezing and protect from light." },
    ],
    notes: [
      "ZPtrop 150 AQ — ZPHC Pro-Line",
      "Premixed HGH • 10 vials × 15 IU (total 150 IU)",
      "Cold-chain packed • tamper-evident vials • discreet, tracked worldwide shipping.",
    ],
  },
  {
    slug: "zptrop-hgh-zphc-90-iu-premixed",
    name: "Zptrop 90 AQ ZPHC - Premixed",
    sku: "HGH90-AQ-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-90IU-KIT-ZPHC-2.jpg",
    sourcePriceUsd: 149.0,
    specs: [
      { label: "Ready-to-use formula", value: "fully premixed somatropin solution — no reconstitution required; draw IU directly with an insulin syringe." },
      { label: "Convenient dosing", value: "45 IU per vial (≈ 15 mg total); smooth withdrawal, consistent concentration across all doses." },
      { label: "Araştırma Alanları", value: "tissue-repair, fat-metabolism studies, collagen synthesis, recovery enhancement, sleep & anti-aging models." },
      { label: "Örnek Araştırma Dozu", value: "2–4 IU pre-bed (recovery/anti-aging) • 4–6 IU daily (fat-loss) • 6–8 IU/day (hypertrophy)." },
      { label: "Saklama", value: "ship cold; refrigerate at 2–8 °C after opening; stable for 28 days when kept cold." },
    ],
    notes: [
      "ZPtrop 90 AQ — 191-aa rhGH",
      "Premixed somatropin • 2×45 IU aqueous vials",
      "QC: ≥ 99% purity (HPLC); ultra-low endotoxin; batch-tracked and authenticity-verified.",
    ],
  },
  {
    slug: "zptrop-aq-180-iu-kit-5x36iu-pen-cartridges",
    name: "Zptrop AQ 180 IU Kit (5×36 IU Cartridges for Multi-Use Pen)",
    sku: "HGH180-AQ-CART-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/zptrop-aq-180iu-5-36iu-pen-cartridges-1.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Format", value: "pre-filled single-chamber cartridges containing liquid somatropin (191aa, rDNA origin), designed for compatible multi-use injection pens." },
      { label: "Toplam İçerik", value: "180 IU per kit (5 cartridges × 36 IU / 12 mg each)." },
      { label: "Ready to use", value: "no reconstitution required; precision dosing via multi-use pen system." },
      { label: "Araştırma Alanları", value: "lean-tissue regeneration models, fat-metabolism pathways, recovery protocols, collagen synthesis and sleep-related studies." },
      { label: "Örnek Araştırma Dozu", value: "2–4 IU daily (wellness/recovery models) • 4–6 IU (fat-metabolism studies) • 6–8 IU (hypertrophy-focused protocols)." },
      { label: "Saklama", value: "refrigerate at 2–8 °C; protect from light; do not freeze." },
    ],
    notes: [
      "ZPtrop AQ 180 IU Kit — 191-aa rhGH (Somatropin)",
      "5×36 IU single-chamber cartridges for multi-use pen",
      "QC: high-purity somatropin, sterile pharmaceutical-grade cartridges; batch-verified and authenticity-controlled.",
    ],
  },
]

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function productsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category)
}
