// ZPHC Türkiye ürün kataloğu.
//
// Bu dosya zphcstore.com WooCommerce Store API'sinden üretilmiştir
// (scripts/gen-products.py). Teknik değerler — mg, IU, flakon sayısı,
// saklama sıcaklığı — kaynaktan olduğu gibi taşınır. Hiçbir doz değeri
// elle türetilmez veya tahmin edilmez: ürün sayfasındaki yanlış bir doz
// doğrudan güvenlik sorunudur. Veriyi güncellemek için üreteci yeniden
// çalıştır, elle düzenleme yapma.
//
// Kaynak, ürünleri laboratuvar/araştırma materyali olarak sunar
// ("for research use only"). Bu çerçeve sitede korunur.
//
// sourcePriceUsd kaynak sitedeki USD listesidir, referans içindir.
// Sitede gösterilen fiyat alanı (price) bilinçli olarak boştur.

export type ProductCategory = "peptid" | "hgh" | "aksesuar"

export const categoryLabels: Record<ProductCategory, string> = {
  peptid: "Peptidler",
  hgh: "İnsan Büyüme Hormonu",
  aksesuar: "Aksesuar",
}

export const categoryOrder: ProductCategory[] = ["peptid", "hgh", "aksesuar"]

/** kind: "spec" teknik/sunum verisidir. "claim" üreticinin
 *  etkinlik, kullanım amacı, doz veya yan etki beyanıdır ve sayfada
 *  ayrı bir bölümde, kaynağı belirtilerek gösterilir. */
export interface ProductSpec {
  label: string
  value: string
  kind: "spec" | "claim"
}

export interface Product {
  slug: string
  name: string
  sku?: string
  category: ProductCategory
  /** lib/peptides.ts içindeki ansiklopedi kaydı; doluysa ürün sayfası
   * mekanizma, kanıt seviyesi ve PubMed referanslarını oradan çeker. */
  peptideSlug?: string
  image?: string
  /** Kaynak sitedeki USD fiyatı. Referans; sayfada gösterilmez. */
  sourcePriceUsd?: number
  /** Sitede gösterilecek fiyat. Şimdilik boş. */
  price?: string
  specs: ProductSpec[]
  notes: string[]
}

export const products: Product[] = [
  {
    slug: "aicar-250mg-total-5x50mg-zphc",
    name: "AICAR ZPHC — 250 mg (5 vials × 50 mg)",
    sku: "AIC250-ZPHC",
    category: "peptid",
    peptideSlug: "aicar",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/aicar-50mg-vial-250mg-kit-zphc-1.jpg",
    sourcePriceUsd: 79.0,
    specs: [],
    notes: [],
  },
  {
    slug: "aod-9604-5mg-with-bacteriostatic-water-zphc",
    name: "AOD 9604 5mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "AOD9604-5-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/aod-9604-5mg-vial-zphc-1.jpg",
    sourcePriceUsd: 31.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 5 mg liyofilize AOD 9604 peptidi + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Peptid Profili", value: "İnsan büyüme hormonunun modifiye fragmanı (HGH 176-191), laboratuvar sınıfı sentetik peptid.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen çözücüyü ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Lipoliz modelleri, yağ dokusu çalışmaları, metabolik yolak araştırmaları ve kilo düzenlenmesi analizleri.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında doğrulanmış ve orijinalliği korunmuş; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "AOD 9604 5 mg — sentetik büyüme hormonu fragmanı",
      "Liyofilize toz + bakteriyostatik su",
    ],
  },
  {
    slug: "aod9604-2-5mg-5x2-5mg-zphc",
    name: "AOD 9604 ZPHC — 12.5 mg (5 vials × 2.5 mg)",
    sku: "AOD125-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/AOD-9604-12.5mg-kit-zphc-2.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Mekanizma", value: "IGF-1 veya kan glukozunu yükseltmeden lipolizi artırdığı ve lipogenezi engellediği belirtilen fragment 176-191 analoğu.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 2,5 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz oda sıcaklığında güvenle gönderilir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca günde deri altı 250–500 µg (sabah/akşam bölünerek).", kind: "claim" },
    ],
    notes: [
      "AOD 9604 — hedefli yağ kaybı peptidi",
      "5 liyofilize flakon × 2,5 mg (toplam 12,5 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "aod9604-25mg-5x5mg-zphc",
    name: "AOD 9604 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "AOD25-ZPHC",
    category: "peptid",
    peptideSlug: "aod-9604",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/AOD-9604-25mg-kit-zphc-1.jpg",
    sourcePriceUsd: 125.0,
    specs: [
      { label: "Mekanizma", value: "Glukoz veya IGF-1'i yükseltmeden lipolizi artırdığı ve lipogenezi baskıladığı belirtilen fragment 176-191 analoğu.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 5 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz gönderim sırasında oda sıcaklığında stabildir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca günde deri altı 250–500 µg (sabah/akşam bölünerek).", kind: "claim" },
    ],
    notes: [
      "AOD 9604 — hedefli yağ kaybı peptidi",
      "5 liyofilize flakon × 5 mg (toplam 25 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda orijinallik için kazı-kazan kod bulunur.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "zphc-bpc-157-20mg-with-bacteriostatic-water",
    name: "BPC-157 20mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "BPC157-20-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/bpc-157-20mg-vial-zphc-1.jpg",
    sourcePriceUsd: 83.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 20 mg liyofilize BPC-157 peptidi + rekonstitüsyon için 1 flakon steril çözücü.", kind: "spec" },
      { label: "Peptid Profili", value: "BPC-157 (Body Protection Compound), laboratuvar sınıfı sentetik peptid.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen çözücüyü ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Doku onarımı modelleri, anjiyogenez çalışmaları, gastrointestinal araştırmalar, hücresel rejenerasyon yolakları.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında doğrulanmış ve orijinallik kontrollü; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "BPC-157 20 mg — sentetik peptid",
      "Liyofilize toz + steril çözücü",
    ],
  },
  {
    slug: "bpc157-25mg-5x5mg-zphc",
    name: "BPC-157 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "BPC15725-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/BPC-157-25mg-Kit-ZPHC-2.jpg",
    sourcePriceUsd: 99.0,
    specs: [
      { label: "Hızlı doku onarımı", value: "Peptidin tendon, bağ, kas ve sindirim sistemi mukozasının iyileşmesini hızlandırdığı belirtilir.", kind: "claim" },
      { label: "Antiinflamatuvar destek", value: "Ağrı ve şişliği azaltmaya yardımcı olurken kolajen sentezini artırdığı belirtilir.", kind: "claim" },
      { label: "Liyofilize Saflık", value: "Berrak çözelti için her 5 mg flakonu 1–2 ml bakteriyostatik su ile sulandırın.", kind: "spec" },
      { label: "Doz Rehberi", value: "4–6 hafta boyunca günde 1–2 kez, yaralanma bölgesine yakın deri altı 200–500 mcg; sulandırılmış flakonu buzdolabında saklayın.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz; kazı-kazan kod doğrulaması.", kind: "spec" },
    ],
    notes: [
      "Farma sınıfı BPC-157 — 5 flakon × 5 mg (toplam 25 mg)",
      "Yalıtımlı dünya çapında gönderim • gizlilik esaslı ambalaj • çok dilli destek.",
    ],
  },
  {
    slug: "cagrilintide-25mg-zphc",
    name: "Cagrilintide (25mg) ZPHC",
    sku: "CAGRI25-ZPHC",
    category: "peptid",
    peptideSlug: "cagrilintide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/Cagrilintide-25mg-KIT-ZPHC-3.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Amilin reseptör analoğu", value: "Güçlü iştah baskılanması ve kalori alımının azaltılması üzerine araştırılmaktadır.", kind: "claim" },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥%98,9 saflık (HPLC); GMP ve ISO 17034:2016 standartlarında üretilir, ZPHC kazı-kazan kod doğrulaması içerir.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Ürünle verilen steril çözücüyle birleştirin; çözünene dek hafifçe çevirin. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; tedavi veya insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [
      "Cagrilintide — ZPHC Pro-Line",
      "5 liyofilize flakon × 5 mg (toplam 25 mg) + steril çözücü",
      "Tokluk ve mide boşalması: tokluk sinyallerini güçlendirdiği ve mide boşalmasını yavaşlatarak kilo yönetimi sonuçlarını iyileştirdiği belirtilir.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "double-burn-mix-5mg-5x5mg-zphc",
    name: "Double Burn Mix ZPHC — 25 mg total (5 vials × 5 mg)",
    sku: "DOU25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/double-burn-mix-25mg-kit-zphc-7.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Flakon Başına Formül", value: "AOD 9604 2,5 mg · FRAG 176-191 2,5 mg.", kind: "spec" },
      { label: "Sinerjik etki", value: "Her iki fragmanın da yağ dokusunu hedeflediği, lipolizi hızlandırırken yeni yağ depolanmasını engellediği ve IGF-1 ya da glukoz yükselmesine yol açmadığı belirtilir.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 5 mg/ml; hafifçe çevirin, köpürtmeyin.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz oda sıcaklığında güvenle gönderilir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "Kardiyodan 30 dk önce, günde bir veya iki kez deri altı 250–500 µg; kür süresi 4–6 hafta.", kind: "claim" },
    ],
    notes: [
      "Double Burn Mix — çift yolaklı yağ kaybı peptidi",
      "5 liyofilize flakon × 5 mg (toplam 25 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "epithalon-50mg-with-bacteriostatic-water-zphc",
    name: "Epithalon 50mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "EPITH50-ZPHC",
    category: "peptid",
    peptideSlug: "epithalon",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/EPITHALON-50MG-VIAL-ZPHC-8.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 50 mg liyofilize Epithalon + rekonstitüsyon için 1 flakon steril çözücü.", kind: "spec" },
      { label: "Peptid Profili", value: "Epithalon (Epitalon), sentetik tetrapeptid (Ala-Glu-Asp-Gly), laboratuvar sınıfı materyal.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen çözücüyü ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Telomeraz aktivitesi çalışmaları, hücresel yaşlanma modelleri, sirkadiyen ritim araştırmaları, antioksidan yolak analizleri.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; ışıktan koruyun.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında izlenir ve orijinalliği doğrulanır; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "Epithalon 50 mg — sentetik tetrapeptid",
      "Liyofilize toz + steril çözücü",
    ],
  },
  {
    slug: "ghk-cu-60mg-with-bacteriostatic-water-zphc",
    name: "GHK-Cu 60mg Kit ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "GHKCU60-ZPHC",
    category: "peptid",
    peptideSlug: "ghk-cu",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/GHK-CU-60MG-KIT-1VIAL-ZPHC-3.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 60 mg liyofilize GHK-Cu (bakır peptidi) + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Peptid Profili", value: "GHK-Cu (glisil-L-histidil-L-lizin bakır kompleksi), laboratuvar sınıfı sentetik peptid.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen bakteriyostatik suyu ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Kolajen sentezi modelleri, doku rejenerasyonu çalışmaları, cilt onarım yolakları, antiinflamatuvar araştırmalar.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; ışıktan koruyun.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında doğrulanmış ve orijinallik kontrollü; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "GHK-Cu 60 mg — bakır peptidi",
      "Liyofilize toz + bakteriyostatik su",
    ],
  },
  {
    slug: "ghk-cu-50mg-zphc",
    name: "GHK-Cu ZPHC — 50 mg KIT (5 vials × 10 mg)",
    sku: "GHKCU50-ZPHC",
    category: "peptid",
    peptideSlug: "ghk-cu",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/GHK-CU-50MG-KIT-5VIAL-ZPHC-1.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Rejeneratif bakır peptidi", value: "Cilt onarımının güçlendirilmesi, kolajen uyarımı ve dermal yapının iyileştirilmesi üzerine araştırılmaktadır.", kind: "claim" },
      { label: "Yaşlanma karşıtı etki", value: "Hücresel yenilenmeyi, elastikiyetin geri kazanılmasını ve görünür yaşlanma belirtilerinin azalmasını desteklediği belirtilir.", kind: "claim" },
      { label: "Saç büyümesi desteği", value: "Folikül sağlığını desteklediği ve saç yoğunluğunu hedefleyen araştırma protokollerinde kullanılabildiği belirtilir.", kind: "claim" },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥%98,9 saflık (HPLC); GMP ve ISO 17034:2016 kapsamında üretilir, ZPHC kazı-kazan kod doğrulaması içerir.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Ürünle verilen steril çözücüyü ekleyin; çözünene dek hafifçe çevirin. 2–8 °C'de saklayın.", kind: "spec" },
    ],
    notes: [
      "GHK-Cu (Bakır Tripeptid-1) — ZPHC",
      "5 liyofilize flakon × 10 mg (toplam 50 mg) + steril çözücü",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "ghrp-2-25mg-5x5mg-zphc-2",
    name: "GHRP-2 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "GHRP225-ZPHC",
    category: "peptid",
    peptideSlug: "ghrp-2",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/GHRP-2-25mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "GH pulsu güçlendirici", value: "Güçlü grelin reseptör peptidinin hipofizden büyüme hormonu salınımını artırdığı belirtilir.", kind: "claim" },
      { label: "Doz Rehberi", value: "6–8 hafta boyunca günde 2–3 kez (yatmadan önce ve antrenman sonrası) deri altı 100–300 mcg; sulandırılmış flakonu buzdolabında saklayın.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz; kazı-kazan kod doğrulaması.", kind: "spec" },
    ],
    notes: [
      "Farma sınıfı GHRP-2 — 5 flakon × 5 mg (toplam 25 mg)",
      "Toparlanma ve yağ kaybı: kas onarımını desteklediği, uyku kalitesini iyileştirdiği ve lipolizi artırdığı belirtilir.",
      "Saf 5 mg liyofilize flakon: 2500 mcg/ml çözelti için 2 ml bakteriyostatik su ile sulandırın.",
      "Sıcaklık kontrollü gönderim • gizlilik esaslı ambalaj • takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "ghrp-6-25mg-5x5mg-zphc",
    name: "GHRP-6 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "GHRP625-ZPHC",
    category: "peptid",
    peptideSlug: "ghrp-6",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/GHRP-6-25mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [],
    notes: [],
  },
  {
    slug: "glow-pro-mix-60mg-bpc157-tb500-ghkcu-zphc",
    name: "Glow Pro Mix 60mg ZPHC - (BPC-157 + TB-500 + GHK-Cu)",
    sku: "GLOWMIX-60-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/glow-pro-mix-60mg-zphc-1.jpg",
    sourcePriceUsd: 129.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 60 mg liyofilize peptid karışımı + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Peptid Profili", value: "BPC-157, TB-500 (Timozin Beta-4 fragmanı) ve GHK-Cu (bakır peptidi) kombinasyonu.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen bakteriyostatik suyu ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Doku onarımı çalışmaları, kolajen sentezi modelleri, cilt rejenerasyonu yolakları, toparlanma ve anjiyogenez araştırmaları.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında doğrulanmış ve orijinallik kontrollü; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "Glow Pro Mix 60 mg — ileri peptid karışımı",
      "BPC-157 + TB-500 + GHK-Cu",
    ],
  },
  {
    slug: "hgh-fragment-176-191-50mg-5x10mg-zphc",
    name: "HGH FRAGMENT 176-191aa (50MG) ZPHC",
    sku: "HGHF50-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/hgh-fragment-10mg-vial-50mg-kit-ZPHC-7.jpg",
    sourcePriceUsd: 147.0,
    specs: [
      { label: "Seçici yağ kaybı", value: "Fragment 176-191'in glukoz veya IGF-1'i yükseltmeden lipolizi artırdığı ve lipogenezi engellediği belirtilir.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "2 ml bakteriyostatik su ekleyin → 5 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırıldıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz oda sıcaklığında güvenle gönderilir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca, kardiyodan 30 dk önce, günde 1–3 kez deri altı 250–500 µg.", kind: "claim" },
    ],
    notes: [
      "HGH Fragment 176-191 — hedefli lipolitik peptid",
      "5 liyofilize flakon × 10 mg (toplam 50 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "zphc-hgh-fragment-176-191-5mg",
    name: "HGH Fragment 176-191 5mg ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "HGHFRAG-5-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/HGH-fragment-5mg-vial-5mg-kit-ZPHC-3.jpg",
    sourcePriceUsd: 29.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 5 mg liyofilize HGH Fragment 176-191 + rekonstitüsyon için 1 flakon steril çözücü.", kind: "spec" },
      { label: "Peptid Profili", value: "İnsan büyüme hormonunun sentetik fragmanı (176-191 amino asitleri), laboratuvar sınıfı materyal.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen çözücüyü ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Lipoliz modelleri, metabolik yolak çalışmaları, yağ dokusu araştırmaları ve enerji düzenlenmesi analizleri.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril flakon, parti bazında doğrulanmış ve orijinallik kontrollü; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "HGH Fragment 176-191 5 mg — büyüme hormonu fragmanı",
      "Liyofilize peptid + steril çözücü",
    ],
  },
  {
    slug: "hgh-fragment-176-191-12-5mg-5x2-5mg-zphc",
    name: "HGH Fragment 176-191 ZPHC — 12.5 mg (5 vials × 2.5 mg)",
    sku: "HGHF125-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/HGH-fragment-5mg-vial-25mg-kit-ZPHC-8.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Hedefli yağ kaybı", value: "Fragment 176-191'in kan şekerini veya IGF-1'i yükseltmeden lipolizi tetiklediği belirtilir.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 2,5 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz oda sıcaklığında güvenle gönderilir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca, kardiyodan 30 dk önce, günde 1–3 kez deri altı 250–500 µg.", kind: "claim" },
    ],
    notes: [
      "HGH Fragment 176-191 — seçici lipolitik peptid",
      "5 liyofilize flakon × 2,5 mg (toplam 12,5 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; kazı-kazan kod doğrulamalı kutu.",
      "Soğuk zincir ambalaj · kurcalamaya karşı korumalı flakonlar · gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "hgh-fragment-176-191-25mg-5x5mg-zphc",
    name: "HGH Fragment 176-191 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "HGHF25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/HGH-fragment-5mg-vial-25mg-kit-ZPHC-8-1.jpg",
    sourcePriceUsd: 125.0,
    specs: [
      { label: "Seçici yağ kaybı", value: "Fragment 176-191'in kan glukozunu veya IGF-1'i yükseltmeden lipolizi artırdığı ve lipogenezi baskıladığı belirtilir.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "2 ml bakteriyostatik su ekleyin → 2,5 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz oda sıcaklığındaki gönderimde stabildir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca, kardiyodan 30 dk önce, günde 1–3 kez deri altı 250–500 µg.", kind: "claim" },
    ],
    notes: [
      "HGH Fragment 176-191 — hedefli lipolitik peptid",
      "5 liyofilize flakon × 5 mg (toplam 25 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.",
      "Soğuk zincir ambalaj · kurcalamaya karşı korumalı flakonlar · gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "hp-hcg-5000iu-vial-zphc",
    name: "HP-hCG ZPHC — 5 000 IU (1 lyophilized vial)",
    sku: "HCG5000-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2023/05/hp-hcg.jpg",
    sourcePriceUsd: 55.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "İnsan koryonik gonadotropini (hCG)", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 5000 IU", kind: "spec" },
      { label: "Hacim", value: "1 flakon, her biri 5000 IU", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Hormon tedavisi, PCT, kadın ve erkekte infertilite tedavisi ve testosteron üretiminin düzenlenmesi", kind: "claim" },
      { label: "Etki", value: "Erkeklerde testosteron üretimini uyardığı, kadınlarda ovülasyonu desteklediği belirtilir. Gebeliğin erken evrelerinin sürdürülmesine yardımcı olduğu ve kilo verme protokollerinde kullanılabildiği ifade edilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin önerdiği şekilde; genellikle PCT'de veya fertilite tedavilerinin parçası olarak kullanılır", kind: "claim" },
      { label: "Yan Etkiler", value: "Baş ağrısı, sinirlilik, huzursuzluk, depresyon, şişlik ve olası alerjik reaksiyonlar", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "hp-hcg-1000iu-zphc",
    name: "HP-hCG ZPHC — 5 000 IU kit (5 vials × 1 000 IU)",
    sku: "HCG1000-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2023/12/hp-hcg-1000-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "İnsan koryonik gonadotropini (hCG)", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 1000 IU", kind: "spec" },
      { label: "Hacim", value: "5 flakon", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Hormon tedavisi, infertilite tedavisi, kür sonrası tedavi (PCT)", kind: "claim" },
      { label: "Etki", value: "Testosteron üretimini uyardığı, fertiliteyi desteklediği ve anabolik steroid kürleri sırasında ve sonrasında hormon düzenlenmesine yardımcı olduğu belirtilir", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin önerdiği şekilde; genellikle PCT'de veya fertilite tedavilerinin parçası olarak kullanılır", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: baş ağrısı, sinirlilik, huzursuzluk ve alerjik reaksiyonlar", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "igf1-lr3-1mg-5x0p2mg-zphc",
    name: "IGF-1 LR3 ZPHC — 1 mg (5 vials × 0.2 mg)",
    sku: "IGF1-ZPHC",
    category: "peptid",
    peptideSlug: "igf-1-lr3",
    image: "https://zphcstore.com/wp-content/uploads/2023/08/igf-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Üretici", value: "ZPHC (Zhengzhou Pharmaceutical Co. Ltd)", kind: "spec" },
      { label: "Etkin Madde", value: "IGF-1 LR3 (İnsülin benzeri büyüme faktörü 1, Long R3)", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 200 mcg", kind: "spec" },
      { label: "Hacim", value: "5 flakon", kind: "spec" },
      { label: "Form", value: "Bakteriyostatik su ile rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Kas büyümesi, yağ metabolizması ve yaşlanma karşıtı faydalar", kind: "claim" },
      { label: "Etki", value: "IGF-1 LR3'ün protein sentezini ve azot tutulumunu artırarak kas büyümesini desteklediği belirtilir. Ayrıca yağ metabolizmasına katkı sağladığı, vücut kompozisyonunu iyileştirdiği ve hücre yenilenmesi ile onarımını destekleyerek yaşlanma karşıtı etki gösterdiği ifade edilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Bakteriyostatik su ile rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyoneli tarafından kişiye özel belirlenir", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: hipoglisemi, eklem ağrısı, baş ağrısı ve şişlik", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "ipamorelin-25mg-5x5mg-zphc",
    name: "Ipamorelin ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "IPA25-ZPHC",
    category: "peptid",
    peptideSlug: "ipamorelin",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Ipamorelin-25mg-Kit-ZPHC-3.jpg",
    sourcePriceUsd: 118.0,
    specs: [
      { label: "Büyüme hormonu artışı", value: "Seçici grelin reseptör agonistinin kortizol yükselmesine yol açmadan GH ve IGF-1 düzeylerini artırdığı belirtilir.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz, mikro filtrelenmiş.", kind: "spec" },
      { label: "Doz Rehberi", value: "6–8 hafta boyunca antrenman sonrası veya yatmadan önce deri altı 200–300 mcg; sulandırılmış flakonu buzdolabında saklayın.", kind: "claim" },
    ],
    notes: [
      "Farma sınıfı Ipamorelin — 5 flakon × 5 mg (toplam 25 mg)",
      "Toparlanma ve yağ kaybı: yağsız kas kütlesinin korunmasını, daha derin REM uykusunu ve hızlanmış iyileşmeyi desteklediği belirtilir.",
      "Kurcalamaya karşı korumalı kutuda mühürlü flakonlar • kazı-kazan kod doğrulaması • takip edilebilir dünya çapında gönderim.",
    ],
  },
  {
    slug: "l-glutathione-3000mg-kit-zphc",
    name: "L-Glutathione ZPHC - 3000 mg Kit (5×600 mg Vials + Diluent)",
    sku: "GLUT3000-ZPHC",
    category: "peptid",
    peptideSlug: "glutathione",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/L-GLUTATIONE-3000MG-KIT-ZPHC-5.jpg",
    sourcePriceUsd: 59.0,
    specs: [
      { label: "Hücresel yaşlanma karşıtı destek", value: "İndirgenmiş GSH'nin hücre içi antioksidan kapasiteyi yenilediği ve oksidatif stres belirteçlerine karşı koyduğu belirtilir.", kind: "claim" },
      { label: "Esnek rekonstitüsyon", value: "Her 600 mg flakon, ürünle verilen çözücüyle eşleşerek araştırma modelleri için özel konsantrasyon ayarına imkân tanır.", kind: "claim" },
      { label: "Stabilite korunur", value: "Tüm flakonlardaki azot örtüsü, tiyol grubunu saklama ve taşıma sırasında oksidasyondan korur.", kind: "claim" },
      { label: "Örnek araştırma protokolü", value: "600–1200 mg oksidatif stres modülasyonu modelleri; redoks döngüsünü güçlendirmek için C vitamini ile sinerjik kullanım.", kind: "claim" },
      { label: "Profi-Line Kalite Kontrolü", value: "Sertifikalı Referans Materyal (CRM), ≥%99 saflık (HPLC), sterilite ve endotoksin onaylı, kazı-kazan kod doğrulaması.", kind: "claim" },
    ],
    notes: [
      "L-Glutatyon (indirgenmiş) — farma sınıfı antioksidan tripeptid",
      "5 × 600 mg liyofilize flakon + 1 × steril çözücü • toplam 3000 mg",
      "Soğuk zincir sınıfı • kurcalamaya karşı korumalı kapaklar • yalnızca ihracata yönelik çok flakonlu sunum.",
    ],
  },
  {
    slug: "ll-37-zphc-25mg-kit",
    name: "LL-37 ZPHC - 25mg KIT (5×5 mg)",
    sku: "LL37-25-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/LL-37-25MG-KIT-ZPHC-3.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Konak savunma peptidi", value: "LL-37'nin araştırma ortamlarında bağışıklık modellemesi, bariyer bütünlüğü ve antimikrobiyal yanıt çalışmalarında kullanıldığı belirtilir.", kind: "claim" },
      { label: "Liyofilize Saflık", value: "5 mg dondurularak kurutulmuş flakonlar, hassas peptid dozlaması için kontrollü rekonstitüsyon sağlar.", kind: "spec" },
      { label: "Stabilite güvencesi", value: "Azot dolgulu borosilikat flakonlar • eşleştirilmiş steril çözücü • CRM sınıfı sentez.", kind: "claim" },
    ],
    notes: [
      "LL-37 — insan katelisidin antimikrobiyal peptidi (AMP)",
      "5 × 5 mg flakon • toplam 25 mg",
      "Kalite kontrolü ve orijinallik: ISO/GMP üretim • HPLC ≥%99 saflık • holografik kazı-kazan kod doğrulaması.",
    ],
  },
  {
    slug: "mots-c-20mg-with-bacteriostatic-water-zphc",
    name: "MOTS-c 20mg Kit ZPHC (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "MOTSC-20-ZPHC",
    category: "peptid",
    peptideSlug: "mots-c",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/mots-c-20mg-zphc-1.jpg",
    sourcePriceUsd: 99.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 20 mg liyofilize MOTS-c peptidi + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Peptid Profili", value: "MOTS-c (12S rRNA mitokondriyal açık okuma çerçevesi), laboratuvar sınıfı sentetik peptid.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen bakteriyostatik suyu ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Metabolik düzenleme çalışmaları, mitokondriyal fonksiyon araştırmaları, glukoz metabolizması modelleri, hücresel enerji yolağı analizleri.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Liyofilize tozu serin ve kuru bir yerde saklayın; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında muhafaza edin; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı steril cam flakon, parti bazında doğrulanmış ve orijinallik kontrollü; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "MOTS-c 20 mg — mitokondri kaynaklı peptid",
      "Liyofilize toz + bakteriyostatik su",
    ],
  },
  {
    slug: "mega-mass-mix-10mg-5x10mg-zphc",
    name: "Mega Mass Mix ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "MEG50-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Mega-Mass-50mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Flakon Başına Formül", value: "GHRP-6 5 mg · CJC-1295 5 mg.", kind: "spec" },
      { label: "Çift etki", value: "GHRP-6 grelin reseptörlerini tetikleyerek keskin bir GH pulsu ve açlık artışı oluşturur; CJC-1295 ise GHRH sinyalini uzatarak GH salınımını sürdürür.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 10 mg/ml; hafifçe çevirin, çalkalamayın.", kind: "spec" },
      { label: "Saklama", value: "Karıştırdıktan sonra 2–8 °C'de buzdolabında saklayın; dondurularak kurutulmuş toz gönderim sırasında oda sıcaklığında stabildir.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca, öğün veya antrenman öncesi günde 3 kez, her peptidden deri altı 100–200 µg (0,02–0,04 ml).", kind: "claim" },
    ],
    notes: [
      "Mega Mass Mix — büyüme hormonu ve iştah güçlendirici",
      "5 liyofilize flakon × 10 mg (toplam 50 mg)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "melanotan-2-10mg-bacteriostatic-water-zphc",
    name: "Melanotan-2 ZPHC — 10 mg (1 lyophilized vial)",
    sku: "MEL10-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2024/06/melanotan-2.jpg",
    sourcePriceUsd: 20.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "Melanotan-2", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 10 mg", kind: "spec" },
      { label: "Hacim", value: "1 flakon + bakteriyostatik su", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Ciltte bronzlaşma, foto-koruma ve olası iştah baskılanması", kind: "claim" },
      { label: "Etki", value: "Melanotan-2'nin vücutta melanin üretimini uyararak uzun süreli UV maruziyeti olmadan koyu, doğal bir bronzluk oluşturduğu belirtilir. Ayrıca UV radyasyonuna karşı bir miktar koruma sağladığı ve iştahı azaltabildiği ifade edilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyoneli tarafından belirlenir; genellikle düşük dozla başlanıp kademeli artırılır", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: bulantı, ciltte kızarma, libido artışı ve benlerde veya çillerde koyulaşma", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "melanotan-2-30mg-aq-pen-zphc",
    name: "Melanotan-II (AQ Pen) ZPHC — 30 mg Premixed",
    sku: "MT2AQ30-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/mt2-30mg-aq-pen-ZPHC-1.jpg",
    sourcePriceUsd: 49.0,
    specs: [
      { label: "Kullanıma Hazır", value: "Su bazlı MT-2 önceden çözünmüş hâlde gelir — flakon, rekonstitüsyon ve enjektör gerekmez.", kind: "spec" },
      { label: "Ayarlanabilir doz", value: "Her tık 150 µg verir; 10 tık = 1,5 mg. Dereceli pencere kalan hacmi gösterir.", kind: "claim" },
      { label: "Önerilen araştırma programı", value: "5 gün boyunca günde 250 µg (≈ 2 tık) → ardından istenen tona ulaşana dek haftada iki kez 500 µg idame.", kind: "claim" },
      { label: "Saklama", value: "Soğuk zincirle gönderilir; açıldıktan sonra 2–8 °C'de buzdolabında saklayın, 30 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "Melanotan-II (MT-2) — hazır sulu çözelti kalemi",
      "Toplam 30 mg • 200 × 150 µg tık",
      "Hızlı bronzlaşma ve foto-koruma: α-MSH reseptörlerini uyararak daha koyu taban pigmenti ve azalmış UV hasarı sağladığı belirtilir.",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; kalem sterilize edilmiş ve kurcalamaya karşı korumalıdır.",
    ],
  },
  {
    slug: "multi-use-pen-36iu-cartridges-zphc",
    name: "Multi-Use Pen ZPHC (For 36 IU Cartridges)",
    sku: "PEN-MU-ZPHC",
    category: "aksesuar",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/multi-use-pen-for-36-iu-zphc-1.jpg",
    sourcePriceUsd: 30.0,
    specs: [
      { label: "Uyumluluk", value: "ZPTROP 36 IU tek hazneli kartuşlarla kullanım için tasarlanmıştır.", kind: "spec" },
      { label: "Cihaz tipi", value: "Yeniden kullanılabilir hassas dozlama kalemi (klinik olmayan cihaz).", kind: "claim" },
      { label: "İşlev", value: "Kontrollü uygulama için ayarlanabilir IU dozlama mekanizması.", kind: "claim" },
      { label: "Tasarım", value: "Şeffaf doz gösterge penceresine sahip dayanıklı alüminyum gövde.", kind: "claim" },
      { label: "Kullanım", value: "Yalnızca araştırma amaçlıdır; tanı veya tedavi uygulamaları için tasarlanmamıştır.", kind: "claim" },
      { label: "Model", value: "ZP-MU36V1.", kind: "claim" },
    ],
    notes: [
      "ZPHC Çok Kullanımlık Kalem — yeniden kullanılabilir dozlama cihazı",
      "36 IU kartuşlarla uyumlu",
    ],
  },
  {
    slug: "nad-plus-2500mg-zphc",
    name: "NAD+ ZPHC — 2500 mg KIT (5 vials × 500 mg)",
    sku: "NAD2500-ZPHC",
    category: "peptid",
    peptideSlug: "nad-nmn",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/NAD-2500MG-KIT-5VIAL-ZPHC-1.jpg",
    sourcePriceUsd: 139.0,
    specs: [
      { label: "Hücresel enerji desteği", value: "ATP üretimi, mitokondriyal verimlilik ve genel metabolik fonksiyon için temel kofaktör.", kind: "claim" },
      { label: "Longevity yolakları", value: "Sirtuin aktivasyonu (SIRT1-7), DNA onarım mekanizmaları ve sağlıklı yaşlanma araştırma modellerinde rol alır.", kind: "claim" },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥%98,9 saflık (HPLC); GMP ve ISO 17034:2016 kapsamında üretilir, ZPHC kazı-kazan kod doğrulaması içerir.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Ürünle verilen steril çözücüyle birleştirin; tamamen çözünene dek hafifçe çevirin. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; tedavi amaçlı kullanım için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [
      "NAD+ (Nikotinamid Adenin Dinükleotid) — ZPHC Pro-Line",
      "5 liyofilize flakon × 500 mg (toplam 2500 mg) + steril çözücü",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "reta-60mg-dual-cartridge-sterile-water-zphc",
    name: "Reta 60mg PEN ZPHC - (Dual-Chamber Cartridge + Sterile Water)",
    sku: "RET60PEN-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/reta-60mg-pen-dual-cartrige-zphc-1.jpg",
    sourcePriceUsd: 359.0,
    specs: [
      { label: "Çift hazneli kartuş (60 mg)", value: "Bir haznede 60 mg liyofilize toz, diğer haznede enjeksiyonluk steril su bulunur; bileşenler aktivasyona kadar ayrı kalır, karışım kullanımdan hemen önce gerçekleşir.", kind: "claim" },
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-30mg-aq-pen-zphc",
    name: "Reta ZPHC (AQ pen) — 30 mg Premixed Pen",
    sku: "RET30B-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta30mg.jpg",
    sourcePriceUsd: 219.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-10mg-5x2mg-zphc-2",
    name: "Reta ZPHC — 10 mg (5 vials × 2 mg)",
    sku: "RET10-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta10mg.jpg",
    sourcePriceUsd: 83.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "reta-zphc-120-mg-5-vials-x-24-mg",
    name: "Reta ZPHC — 120 mg (5 vials × 24 mg)",
    sku: "RET120-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/reta120mg.jpg",
    sourcePriceUsd: 589.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-zphc-15-mg-1vial",
    name: "Reta ZPHC — 15 mg (15 mg * 1 vial)",
    sku: "RET15-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/reta15mg.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-20mg-5x4mg-zphc",
    name: "Reta ZPHC — 20 mg (5 vials × 4 mg)",
    sku: "RET20-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta20mg.jpg",
    sourcePriceUsd: 138.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-40mg-5x8mg-zphc",
    name: "Reta ZPHC — 40 mg (5 vials × 8 mg)",
    sku: "RET40-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta40mg.jpg",
    sourcePriceUsd: 239.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "retatrutide-60mg-5x12mg-zphc",
    name: "Reta ZPHC — 60 mg (5 vials × 12 mg)",
    sku: "RET60-ZPHC",
    category: "peptid",
    peptideSlug: "retatrutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/reta60mg.jpg",
    sourcePriceUsd: 339.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "spectros-140iu-hgh-spectrum-pharma",
    name: "SPECTROS 140IU HGH Spectrum Pharma",
    sku: "HGH140-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-140iu-SpectrumPharma.jpg",
    sourcePriceUsd: 239.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 14 IU (toplam 140 IU)", kind: "spec" },
      { label: "Hacim", value: "10 flakon, her biri 14 IU", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Büyüme hormonu tedavisi, kas kütlesi artışı, yağ azaltımı ve yaşlanma karşıtı kullanım", kind: "claim" },
      { label: "Etki", value: "Büyümeyi uyardığı, yağ yakımını desteklediği, yağsız kas kütlesini artırdığı, toparlanmayı iyileştirdiği ve genel canlılığı yükselttiği belirtilir", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin önerdiği şekilde, genellikle günde 2–4 IU", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: eklem ağrısı, su tutulumu, karpal tünel sendromu ve kan şekerinde yükselme", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "spectros-150iu-hgh-spectrum-pharma",
    name: "SPECTROS 150IU HGH Spectrum Pharma",
    sku: "HGH150-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-150iu-SpectrumPharma.jpg",
    sourcePriceUsd: 229.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 150 IU", kind: "spec" },
      { label: "Hacim", value: "1 flakon, her biri 150 IU", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Kas büyümesi, yağ kaybı, yaşlanma karşıtı kullanım, toparlanmanın iyileşmesi, atletik performans artışı", kind: "claim" },
      { label: "Etki", value: "Büyümeyi uyardığı, yağ yakımını desteklediği, yağsız kas kütlesini artırdığı, toparlanmayı iyileştirdiği ve genel canlılığı yükselttiği belirtilir", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Doz kişisel hedeflere göre değişir; sağlık profesyonelinin önerdiği şekilde, genellikle günde 2–4 IU", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: eklem ağrısı, su tutulumu, karpal tünel sendromu ve kan şekerinde yükselme", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "spectros-280iu-hgh-spectrum-pharma",
    name: "SPECTROS 280iu HGH Spectrum Pharma",
    sku: "HGH280-SP",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/05/Spectros-280iu-SpectrumPharma.jpg",
    sourcePriceUsd: 399.0,
    specs: [
      { label: "Üretici", value: "Spectrum Pharma", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 28 IU (toplam 280 IU)", kind: "spec" },
      { label: "Hacim", value: "10 flakon, her biri 28 IU", kind: "spec" },
      { label: "Form", value: "Rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Kas büyümesi, yağ kaybı, yaşlanma karşıtı kullanım, toparlanmanın iyileşmesi, atletik performans artışı", kind: "claim" },
      { label: "Etki", value: "Büyümeyi uyardığı, yağ yakımını desteklediği, yağsız kas kütlesini artırdığı, toparlanmayı iyileştirdiği ve genel canlılığı yükselttiği belirtilir", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Doz kişisel hedeflere göre değişir; sağlık profesyonelinin önerdiği şekilde, genellikle günde 2–4 IU", kind: "claim" },
      { label: "Yan Etkiler", value: "Eklem ağrısı, şişlik, insülin direnci ve karpal tünel sendromu görülebilir", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın; rekonstitüsyon sonrası buzdolabında muhafaza edin", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "semaglutide-10mg-5x2mg-zphc",
    name: "Semaglutide ZPHC — 10 mg (5 vials × 2 mg)",
    sku: "SEM10-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Semaglutide-10mg-ZPHC-2.jpg",
    sourcePriceUsd: 76.0,
    specs: [
      { label: "Araştırma Odağı", value: "İştah baskılanması, mide boşalmasının gecikmesi, insülin duyarlılığında iyileşme ve hızlı yağ kaybı.", kind: "claim" },
      { label: "Haftada Tek Doz Protokolü", value: "Uzun yarı ömrü, haftada tek bir deri altı doza imkân tanır.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 2 mg/ml; hafifçe çevirin, köpürtmeyin. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Titrasyon rehberi (araştırma)", value: "1.–4. hafta → 0,25 mg • 5.–8. hafta → 0,5 mg • iyi tolere edilirse haftada 1 mg'a çıkılır.", kind: "claim" },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥%99 saflık, endotoksin < 0,03 EU/mg; her kutuda orijinallik için kazı-kazan kod bulunur.", kind: "spec" },
    ],
    notes: [
      "Semaglutid — GLP-1 reseptör agonisti",
      "5 liyofilize flakon × 2 mg (toplam 10 mg)",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "semaglutide-20mg-5x4mg-zphc",
    name: "Semaglutide ZPHC — 20 mg (5 vials × 4 mg)",
    sku: "SEM20-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Semaglutide-20mg-ZPHC-5.jpg",
    sourcePriceUsd: 143.0,
    specs: [
      { label: "Araştırma Odağı", value: "Güçlü iştah baskılanması, mide boşalmasının gecikmesi, insülin duyarlılığında iyileşme ve hızlı yağ kaybı.", kind: "claim" },
      { label: "Haftada Tek Doz Protokolü", value: "Uzun yarı ömrü, haftada tek bir deri altı enjeksiyona imkân tanır.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "2 ml bakteriyostatik su ekleyin → 2 mg/ml; hafifçe çevirin, köpürtmeyin. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Titrasyon rehberi (araştırma)", value: "1.–4. hafta → 0,25 mg • 5.–8. hafta → 0,5 mg • iyi tolere edilirse haftada 1 mg'a çıkılır.", kind: "claim" },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥%99 saflık, endotoksin < 0,03 EU/mg; her kutuda orijinallik için kazı-kazan kod bulunur.", kind: "spec" },
    ],
    notes: [
      "Semaglutid — GLP-1 reseptör agonisti",
      "5 liyofilize flakon × 4 mg (toplam 20 mg)",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "semaglutide-5mg-kit-zphc",
    name: "Semaglutide ZPHC — 5 mg (5 vials × 1 mg)",
    sku: "SEM5-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2024/02/semaglutide-zphc.jpg",
    sourcePriceUsd: 44.0,
    specs: [
      { label: "Yeni nesil GLP-1 agonisti", value: "Klinik çalışmalarda iştahı baskıladığı, glisemik kontrolü iyileştirdiği ve sürdürülebilir yağ kaybı sağladığı gösterilmiştir.", kind: "claim" },
      { label: "Haftalık dozlama kolaylığı", value: "Uzun yarı ömrü, haftada bir deri altı enjeksiyona imkân tanır.", kind: "claim" },
      { label: "Basit rekonstitüsyon", value: "Her flakona 1 ml bakteriyostatik su ekleyin → 1 mg/ml çözelti (0,1 ml = 0,1 mg). 2–8 °C'de buzdolabında saklayın.", kind: "claim" },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz; her kutuda kazı-kazan kod doğrulaması.", kind: "spec" },
    ],
    notes: [
      "Semaglutid — 5 liyofilize flakon × 1 mg (toplam 5 mg)",
      "Doz rehberi (araştırma): haftada bir 0,25 mg × 4 hafta → 0,5 mg × 4 hafta → 1 mg idame; yalnızca iyi tolere edilirse artırılır.",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı paket • gizlilik esaslı, takip edilebilir dünya çapında gönderim.",
    ],
  },
  {
    slug: "semaglutide-zphc-50-mg-5-vials-x-10-mg",
    name: "Semaglutide ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "SEM50-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/SEMAGLUTIDE-50MG-KIT-ZPHC-2.jpg",
    sourcePriceUsd: 279.0,
    specs: [
      { label: "Araştırma Odağı", value: "Güçlü iştah baskılanması, mide boşalmasının gecikmesi, insülin duyarlılığında iyileşme ve hızlı yağ kaybı.", kind: "claim" },
      { label: "Haftada Tek Doz Protokolü", value: "Uzun yarı ömrü, haftada tek bir deri altı enjeksiyona imkân tanır.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "2 ml bakteriyostatik su ekleyin → 2 mg/ml; hafifçe çevirin, köpürtmeyin. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Titrasyon rehberi (araştırma)", value: "1.–4. hafta → 0,25 mg • 5.–8. hafta → 0,5 mg • iyi tolere edilirse haftada 1 mg'a çıkılır.", kind: "claim" },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥%99 saflık, endotoksin < 0,03 EU/mg; her kutuda orijinallik için kazı-kazan kod bulunur.", kind: "spec" },
    ],
    notes: [
      "Semaglutid — GLP-1 reseptör agonisti",
      "5 liyofilize flakon × 10 mg (toplam 50 mg)",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "semaglutide-6mg-aq-pen-zphc",
    name: "Semaglutide ZPHC — 6 mg Premixed Pen",
    sku: "SEM6-ZPHC",
    category: "peptid",
    peptideSlug: "semaglutide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/SEMAGLUTIDE-6mg-pen-4.jpg",
    sourcePriceUsd: 105.0,
    specs: [
      { label: "Karıştırma gerektirmez", value: "Tamamen çözünmüş peptid — dozu ayarlayıp deri altına uygulamanız yeterlidir.", kind: "claim" },
      { label: "Metabolik etki", value: "Mide boşalmasını yavaşlattığı, iştahı baskıladığı ve insülin duyarlılığını iyileştirdiği belirtilir.", kind: "claim" },
      { label: "Ayarlanabilir doz hassasiyeti", value: "Her tık 0,25 mg verir; kalem 24 tık sağlar (toplam 6 mg).", kind: "claim" },
      { label: "Önerilen araştırma titrasyonu", value: "Haftada 0,25 mg → tolere edildikçe her 4 haftada bir 0,25 mg artırılarak 1 mg'a kadar.", kind: "claim" },
      { label: "Saklama", value: "Buzla gönderilir; açıldıktan sonra 2–8 °C'de buzdolabında saklayın; soğukta tutulduğunda çözelti 28 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "Semaglutid — GLP-1 reseptör agonisti",
      "6 mg dolu sulu çözelti kalemi • 24 tık × 0,25 mg",
      "Kalite kontrolü: ≥%99 saflık, endotoksin < 0,03 EU/mg; kalem sterilize, kurcalamaya karşı korumalı ve kazı-kazan kod doğrulamalı.",
    ],
  },
  {
    slug: "super-slim-mix-275mg-5x55mg-zphc",
    name: "Super Slim Mix ZPHC — 27,5 mg (5 vials × 5,5 mg)",
    sku: "SUP275-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Super-slim-mix-5.5mg-vial-27.5mg-kit-ZPHC-1.jpg",
    sourcePriceUsd: 149.0,
    specs: [
      { label: "Rekonstitüsyon", value: "1 ml bakteriyostatik su ekleyin → 5,5 mg/ml. 2–8 °C'de saklayın.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca günde bir, deri altı 0,25 – 0,5 ml (≈ 1,4 – 2,8 mg).", kind: "claim" },
    ],
    notes: [
      "Super Slim Mix — üç yolaklı yağ kaybı karışımı",
      "5 liyofilize flakon × 5,5 mg (toplam 27,5 mg)",
      "AOD 9604 2,5 mg: lipolizi artıran ve lipogenezi engelleyen HGH fragmanı.",
      "FRAG 176-191 2,5 mg: seçici yağ azaltımı için yağ dokusunu hedefler.",
      "Adipotide 0,5 mg: kan akışını bozarak adiposit apoptozunu tetikler.",
      "Kalite kontrolü: ≥%99 saflık, endotoksin < 0,03 EU/mg; kazı-kazan kod doğrulamalı kutu.",
    ],
  },
  {
    slug: "super-slim-mix-55mg-5x11mg-zphc",
    name: "Super Slim Mix ZPHC — 55 mg (5 vials × 11 mg)",
    sku: "SUP55-ZPHC",
    category: "peptid",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Super-slim-mix-11mg-55mg-kit-ZPHC-4.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Flakon Başına Formül", value: "AOD 9604 5 mg · FRAG 176-191 5 mg · Adipotide 1 mg.", kind: "spec" },
      { label: "Sinerjik etki", value: "AOD ve FRAG lipolizi hızlandırır; Adipotide yağ hücresi damarlanmasını seçici olarak azaltır.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "2 ml bakteriyostatik su ekleyin → 5,5 mg/ml. Hafifçe çevirin; 2–8 °C'de buzdolabında saklayın.", kind: "spec" },
      { label: "Örnek Araştırma Dozu", value: "4–6 hafta boyunca günde bir, deri altı 0,25 ml (≈ 1,4 mg) – 0,5 ml (≈ 2,8 mg).", kind: "claim" },
      { label: "Farma Sınıfı Kalite Kontrolü", value: "≥%99 saflık, endotoksin < 0,03 EU/mg; her kutuda kazı-kazan kod doğrulaması.", kind: "spec" },
    ],
    notes: [
      "Super Slim Mix — üç yolaklı yağ kaybı karışımı",
      "5 liyofilize flakon × 11 mg (toplam 55 mg)",
      "Soğuk zincir ambalaj · kurcalamaya karşı korumalı flakon · gizlilik esaslı, takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "zphc-tb500-20mg-with-bacteriostatic-water",
    name: "TB-500 20mg Kit (Lyophilized Peptide + Bacteriostatic Water)",
    sku: "TB50020-ZPHC",
    category: "peptid",
    peptideSlug: "tb-500",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/Tb-500-20mg-Kit-ZPHC-1.jpg",
    sourcePriceUsd: 109.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 20 mg liyofilize TB-500 (toz) + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Peptid Profili", value: "TB-500 (Timozin Beta-4 fragmanı), yüksek saflıkta laboratuvar sınıfı materyal.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen bakteriyostatik suyu ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Doku onarımı modelleri, anjiyogenez çalışmaları, toparlanma ve rejenerasyon yolakları, hücresel göç araştırmaları.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Rekonstitüsyon sonrası 2–8 °C'de buzdolabında saklayın; dondurmayın; liyofilize tozu serin ve kuru bir yerde muhafaza edin.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Parti bazında izlenen, hermetik kapalı steril cam flakonlar; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "TB-500 20 mg — Timozin Beta-4 fragmanı",
      "Liyofilize peptid + bakteriyostatik su",
    ],
  },
  {
    slug: "tb500-25mg-5x5mg-zphc",
    name: "TB-500 ZPHC — 25 mg (5 vials × 5 mg)",
    sku: "TB50025-ZPHC",
    category: "peptid",
    peptideSlug: "tb-500",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Tb-500-25mg-Kit-ZPHC-8.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Antiinflamatuvar etki", value: "Şişliği ve yaralanma sonrası tutukluğu azaltmaya yardımcı olduğu belirtilir.", kind: "claim" },
      { label: "Doz Rehberi", value: "4–6 hafta boyunca haftada 2–5 mg (2–3 enjeksiyona bölünerek); ardından idame için 10–14 günde bir 2 mg.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz, kazı-kazan kod doğrulaması.", kind: "spec" },
    ],
    notes: [
      "Farma sınıfı TB-500 (Timozin β-4 fragmanı) — 5 flakon × 5 mg (toplam 25 mg)",
      "Doku ve eklem onarımı: kas, tendon, bağ ve cildin iyileşmesini hızlandırdığı belirtilir.",
      "Saf 5 mg liyofilize flakon: berrak çözelti için 2–3 ml bakteriyostatik su ile sulandırın.",
      "Sıcaklık kontrollü gönderim • gizlilik esaslı ambalaj • takip edilebilir dünya çapında teslimat.",
    ],
  },
  {
    slug: "tirze-zphc-75-mg-dual-cartridge-pen",
    name: "Tirze 75mg Dual Cartridge Pen",
    sku: "TIR75-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/t-75mg.jpg",
    sourcePriceUsd: 339.0,
    specs: [
      { label: "Çift hazneli kartuş (75 mg)", value: "Bir haznede 75 mg liyofilize toz, diğer haznede enjeksiyonluk steril su bulunur; bileşenler aktivasyona kadar ayrı kalır, karışım kullanımdan hemen önce gerçekleşir.", kind: "claim" },
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-zphc-150-mg-5-vials-x-30-mg",
    name: "Tirze ZPHC — 150 mg (5 vials × 30 mg)",
    sku: "TIRZEP150-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/tirzepatide-150mg-zphc.jpg",
    sourcePriceUsd: 699.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-30mg-aq-pen-zphc",
    name: "Tirze ZPHC — 30 mg Premixed Pen",
    sku: "TIR30-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/terzipatide-pen-30mg-zphc.jpg",
    sourcePriceUsd: 189.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-37p5mg-5x7p5mg-zphc",
    name: "Tirze ZPHC — 37.5 mg (5 vials × 7.5 mg)",
    sku: "TIRZEP75-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/terzipatide-37-5-zphc.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "tirzepatide-50mg-5x10mg-zphc",
    name: "Tirze ZPHC — 50 mg (5 vials × 10 mg)",
    sku: "TIRZEP10-ZPHC",
    category: "peptid",
    peptideSlug: "tirzepatide",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/tirzepatide-50mg-zphc.jpg",
    sourcePriceUsd: 259.0,
    specs: [
      { label: "Yalnızca Araştırma Amaçlı", value: "Analitik referans materyali; insan kullanımı için tasarlanmamıştır.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "zphc-ultra-rehab-mix-20mg-bpc157-tb500",
    name: "Ultra Rehab Mix ZPHC - 20mg (BPC-157 + TB-500)",
    sku: "URMIX25-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/ultra-rehab-20mg-kit-zphc-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Bileşim", value: "10 mg BPC-157 ve 10 mg TB-500 (Timozin Beta-4 fragmanı) içeren çift peptidli karışım.", kind: "claim" },
      { label: "Toplam İçerik", value: "Flakon başına 20 mg; hermetik kapalı steril cam kap.", kind: "spec" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda bakteriyostatik su ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Doku onarımı modelleri, tendon/bağ rejenerasyonu çalışmaları, inflamasyon yanıtı yolakları, toparlanma odaklı laboratuvar protokolleri.", kind: "claim" },
      { label: "Örnek araştırma protokolleri", value: "Doz, çalışma tasarımına ve analitik çerçeveye göre değişir.", kind: "claim" },
      { label: "Saklama", value: "Liyofilize tozu serin ve kuru tutun; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında saklayın; dondurmayın.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Yüksek saflıkta peptidler, parti bazında izlenir ve orijinalliği doğrulanır; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "Ultra Rehab Mix 20 mg — BPC-157 + TB-500",
      "10 mg BPC-157 + 10 mg TB-500 | Araştırma Peptid Kiti",
    ],
  },
  {
    slug: "ultra-rehab-mix-50mg-5x10mg-zphc",
    name: "Ultra Rehab Mix ZPHC — 50 mg (BPC-157 5 mg + TB-500 5 mg) — 5 vials × 10 mg",
    sku: "URMIX50-ZPHC",
    category: "peptid",
    peptideSlug: "bpc-157",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Ultra-Rehab-50mg-Kit-ZPHC-3.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Liyofilize Saflık", value: "Her 10 mg flakonu 2 ml bakteriyostatik su ile sulandırarak toplam 5 mg/ml peptid elde edin (ml başına 2,5 mg BPC + 2,5 mg TB).", kind: "spec" },
      { label: "Doz Rehberi", value: "4–6 hafta boyunca haftada 2–5 mg (1–2 ml), 2–3 deri altı enjeksiyona bölünerek; ardından idame için 10–14 günde bir 2 mg.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz; kazı-kazan kod doğrulamalı, kurcalamaya karşı korumalı kutu.", kind: "spec" },
    ],
    notes: [
      "Ultra Rehab Mix — çift peptidli iyileşme kombinasyonu (5 flakon × 10 mg, toplam 50 mg)",
      "Her flakonda BPC-157 5 mg + TB-500 5 mg — tendon, bağ ve kas onarımını hızlandırmayı amaçlayan sinerjik kombinasyon.",
      "Antiinflamatuvar ve koruyucu: şişliği azaltmaya yardımcı olur, kolajen birikimini ve yaralı dokuya kan akışını artırır.",
      "Yalıtımlı dünya çapında gönderim • gizlilik esaslı ambalaj • çok dilli destek.",
    ],
  },
  {
    slug: "wellness-mix-25mg-5x5mg-zphc",
    name: "Wellness Mix ZPHC — 25 mg (Ipamorelin 2.5 mg + CJC-1295 2.5 mg) — 5 vials × 5 mg",
    sku: "WMIX25-ZPHC",
    category: "peptid",
    peptideSlug: "ipamorelin",
    image: "https://zphcstore.com/wp-content/uploads/2025/06/Wellness-Mix-25mg-Kit-ZPHC-5.jpg",
    sourcePriceUsd: 119.0,
    specs: [
      { label: "Çift etki", value: "Ipamorelin 2,5 mg + CJC-1295 2,5 mg, doğal GH ve IGF-1 salınımını güçlendirir.", kind: "claim" },
      { label: "Faydalar", value: "Yağsız kas kütlesinin korunması, yağ oksidasyonu, daha derin uyku ve daha hızlı toparlanma.", kind: "claim" },
      { label: "Araştırma Sınıfı Kalite Kontrolü", value: "ZPHC partileri: ≥%99 saflık, endotoksinsiz, mikro filtrelenmiş.", kind: "spec" },
      { label: "Doz Rehberi", value: "Sulandırılmış 1 flakon = 5 mg; 6–8 hafta boyunca günde 300–500 mcg uygulanır.", kind: "claim" },
    ],
    notes: [
      "Wellness Mix — sinerjik peptid kombinasyonu (5 flakon × 5 mg)",
      "Kurcalamaya karşı korumalı kutuda mühürlü flakonlar • kazı-kazan kod doğrulaması • takip edilebilir dünya çapında gönderim.",
    ],
  },
  {
    slug: "zphc-nad-plus-1000mg-with-bacteriostatic-water",
    name: "ZPHC NAD+ 1000mg Kit (Lyophilized Powder + Bacteriostatic Water)",
    sku: "NAD1000-ZPHC",
    category: "peptid",
    peptideSlug: "nad-nmn",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/NAD-1000MG-KIT-ZPHC-1.jpg",
    sourcePriceUsd: 63.0,
    specs: [
      { label: "Kit İçeriği", value: "1 flakon 1000 mg liyofilize NAD+ + rekonstitüsyon için 1 flakon bakteriyostatik su.", kind: "spec" },
      { label: "Bileşik Profili", value: "β-Nikotinamid Adenin Dinükleotid (okside form), yüksek saflıkta laboratuvar sınıfı materyal.", kind: "claim" },
      { label: "Rekonstitüsyon", value: "Steril koşullarda, ürünle verilen bakteriyostatik suyu ekleyin; tamamen çözünene dek hafifçe çevirin.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Hücresel enerji metabolizması çalışmaları, mitokondriyal fonksiyon modelleri, longevity yolakları, NAD+ restorasyonu araştırmaları.", kind: "claim" },
      { label: "Taşıma ve Muhafaza", value: "Rekonstitüsyon sonrası 2–8 °C'de buzdolabında saklayın; ışıktan koruyun; liyofilize tozu serin ve kuru bir yerde muhafaza edin.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Parti bazında doğrulanmış, hermetik kapalı steril flakonlar; yalnızca araştırma amaçlıdır.", kind: "spec" },
    ],
    notes: [
      "NAD+ 1000 mg — Nikotinamid Adenin Dinükleotid",
      "Liyofilize toz + bakteriyostatik su",
    ],
  },
  {
    slug: "zptrop-144iu-2x72iu-two-chamber-cartridges-zphc",
    name: "ZPTROP 144 IU Kit ZPHC (2×72 IU Two-Chamber Cartridges)",
    sku: "HGH144-AQ-CART-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/zptrop-144iu-two-chamber-cartriges-zphc-2.jpg",
    sourcePriceUsd: 229.0,
    specs: [
      { label: "Format", value: "2 adet hermetik kapalı çift hazneli cam kartuş.", kind: "spec" },
      { label: "Kartuş başına içerik", value: "72 IU (24 mg) somatropin 191aa (rDNA kaynaklı).", kind: "claim" },
      { label: "Çift hazneli sistem", value: "Liyofilize peptid ve steril çözücü, aktivasyon ve karıştırma anına kadar ayrı kalır.", kind: "claim" },
      { label: "Toplam kit", value: "144 IU.", kind: "claim" },
      { label: "Uyumluluk", value: "Uyumlu çok kullanımlık kalem cihazlarıyla kullanım için tasarlanmıştır.", kind: "spec" },
      { label: "Kalite Kontrolü", value: "Sertifikalı referans materyal (CRM), parti bazında doğrulanmış ve orijinalliği korunmuş.", kind: "spec" },
      { label: "Bilgilendirme", value: "Yalnızca profesyonel kullanım içindir.", kind: "spec" },
    ],
    notes: [
      "ZPTROP 144 IU — çift hazneli somatropin kartuşları",
      "2 × 72 IU (24 mg) çift hazneli sistem",
    ],
  },
  {
    slug: "zphc-zptrop-72iu-dual-chamber-pen",
    name: "ZPTROP 72 IU ZPHC Dual-Chamber Pen (24mg)",
    sku: "ZPTAQ72-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/Zptrop-AQ-72IU-pen-ZPHC-2.jpg",
    sourcePriceUsd: 159.0,
    specs: [
      { label: "Format", value: "Ayrı bölmeli steril çift hazneli kalem.", kind: "spec" },
      { label: "İçerik", value: "24 mg (72 IU) liyofilize somatropin 191aa (rDNA kaynaklı) + steril çözücü.", kind: "claim" },
      { label: "Aktivasyon sistemi", value: "Toz ve çözücü aktivasyona kadar ayrı kalır; ilk kullanımdan önce otomatik karışım gerçekleşir.", kind: "claim" },
      { label: "Teslimat", value: "Hassas, IU bazında ayarlanabilir dozlama mekanizması.", kind: "claim" },
      { label: "Kalite Kontrolü", value: "Hermetik kapalı sistem, parti bazında doğrulanmış ve orijinalliği korunmuş.", kind: "spec" },
      { label: "Bilgilendirme", value: "Sertifikalı referans materyal (CRM); yalnızca profesyonel kullanım içindir.", kind: "spec" },
    ],
    notes: [
      "ZPTROP 72 IU — çift hazneli kalem sistemi",
      "24 mg (72 IU) somatropin",
    ],
  },
  {
    slug: "zptrop-hgh-36iu-aq-pen-zphc",
    name: "ZPtrop HGH (AQ pen) ZPHC — 36 IU Premixed Pen",
    sku: "ZPTAQ36-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Zptrop-AQ-36IU-pen-ZPHC-1.jpg",
    sourcePriceUsd: 89.0,
    specs: [
      { label: "Kullanıma Hazır", value: "Tamamen çözünmüş somatropin çözeltisi — flakon veya bakteriyostatik su gerekmez.", kind: "spec" },
      { label: "Mikro hassasiyetli doz ayarı", value: "Her tık ≈0,6 IU (0,2 mg) verir. 60 tık = tam 36 IU.", kind: "claim" },
      { label: "Araştırma Alanları", value: "Yağsız doku onarımı, yağ kaybı, uyku kalitesi, kolajen sentezi ve yaşlanma karşıtı modeller.", kind: "claim" },
      { label: "Önerilen araştırma dozu", value: "Toparlanma/yaşlanma karşıtı için yatmadan önce 2–4 IU • yağ kaybı için sabah/akşam bölünmüş 4–6 IU • hipertrofi protokolleri için 8–10 IU.", kind: "claim" },
      { label: "Saklama", value: "Buzla gönderilir; açıldıktan sonra 2–8 °C'de buzdolabında saklayın. 2–8 °C'de 28 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "ZPtrop İnsan Büyüme Hormonu — 191 aa rhGH",
      "36 IU dolu sulu çözelti kalemi • 60 tık × 0,6 IU",
      "Kalite kontrolü: ≥%99 saflık (HPLC), endotoksin < 0,03 EU/mg; steril, kurcalamaya karşı korumalı kalem ve kazı-kazan kod doğrulaması.",
    ],
  },
  {
    slug: "zptropin-hgh-320iu-zphc",
    name: "ZPtrop HGH 320iu ZPHC",
    sku: "HGH320-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2023/07/zptrop-320-1.jpg",
    sourcePriceUsd: 449.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 32 IU (10,6 mg)", kind: "spec" },
      { label: "Hacim", value: "10 flakon", kind: "spec" },
      { label: "Form", value: "Bakteriyostatik su ile rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Büyüme hormonu tedavisi, kas kütlesi kazanımı, yağ kaybı, yaşlanma karşıtı kullanım", kind: "claim" },
      { label: "Etki", value: "Kas kütlesinde artış, vücut yağında azalma, toparlanmada iyileşme ve yaşlanma karşıtı etkiler dâhil olmak üzere büyüme hormonu tedavisinin faydalarını desteklediği belirtilir. Sporcular ve vücut geliştiriciler tarafından fiziksel performansı ve vücut kompozisyonunu iyileştirmek amacıyla yaygın olarak kullanılır.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin belirlediği dozlarda uygulanır; genellikle günde 2–10 IU aralığındadır.", kind: "claim" },
      { label: "Yan Etkiler", value: "Eklem ağrısı, su tutulumu, insülin direnci ve diyabet riskinde olası artış. Düzenli takip ve sağlık profesyoneline danışılması önerilir.", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-80iu-zphc-bacteriostatic-water",
    name: "ZPtrop HGH 80iu ZPHC + Bacteriostatic Water",
    sku: "HGH80-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2023/07/zptrop-80-1.jpg",
    sourcePriceUsd: 179.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "5 flakon", kind: "spec" },
      { label: "Hacim", value: "5 flakon, rekonstitüsyon için bakteriyostatik su dâhil", kind: "spec" },
      { label: "Form", value: "Bakteriyostatik su ile rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Büyüme hormonu tedavisi, kas kütlesi kazanımı, yağ kaybı, yaşlanma karşıtı kullanım", kind: "claim" },
      { label: "Etki", value: "Kas büyümesini desteklediği, vücut yağını azalttığı, toparlanmayı iyileştirdiği ve yaşlanma karşıtı etki gösterdiği belirtilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin önerdiği şekilde, genellikle günde 2–10 IU.", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: eklem ağrısı, su tutulumu, insülin direnci ve diyabet riskinde artış.", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "zptrop-100iu-zphc",
    name: "ZPtrop HGH ZPHC — 100 IU (1 lyophilized vial)",
    sku: "HGH100-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2024/10/zptrop-hgh-100iu-1.jpg",
    sourcePriceUsd: 189.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "100 IU", kind: "spec" },
      { label: "Hacim", value: "1 flakon", kind: "spec" },
      { label: "Form", value: "Bakteriyostatik su ile rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Büyüme hormonu tedavisi, kas kütlesi kazanımı, yağ kaybı, yaşlanma karşıtı kullanım", kind: "claim" },
      { label: "Etki", value: "Kas büyümesini desteklediği, vücut yağını azalttığı, toparlanmayı iyileştirdiği ve yaşlanma karşıtı etki gösterdiği belirtilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin önerdiği şekilde, genellikle günde 2–10 IU.", kind: "claim" },
      { label: "Yan Etkiler", value: "Olası yan etkiler: eklem ağrısı, su tutulumu, insülin direnci ve diyabet riskinde artış.", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-100iu-aq-vial-zphc",
    name: "ZPtrop HGH ZPHC — 100 IU Premixed Vial",
    sku: "ZPTAQ100-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/07/Zptrop-100-aq-ZPHC-4.jpg",
    sourcePriceUsd: 199.0,
    specs: [
      { label: "Rekonstitüsyon gerekmez", value: "Tamamen çözünmüş somatropin çözeltisi — istenen IU'yu insülin enjektörüyle çekmeniz yeterlidir.", kind: "claim" },
      { label: "Dereceli tıpa", value: "Hassas dozlama için etikette 3 IU (≈ 1 mg) aralıklarla işaretleme; flakon başına 33 tam çekim.", kind: "claim" },
      { label: "Araştırma Alanları", value: "Yağsız doku onarımı, lipoliz, kolajen sentezi, daha derin uyku ve yaşlanma karşıtı modeller.", kind: "claim" },
      { label: "Örnek Araştırma Dozu", value: "Yatmadan önce 2–4 IU (toparlanma/yaşlanma karşıtı) • sabah/akşam bölünmüş 4–6 IU (yağ kaybı) • günde 8–10 IU (hipertrofi).", kind: "claim" },
      { label: "Saklama", value: "Buzla gönderilir; açıldıktan sonra 2–8 °C'de buzdolabında saklayın; soğukta tutulduğunda 28 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "ZPtrop İnsan Büyüme Hormonu — 191 aa rhGH",
      "100 IU hazır sulu çözelti flakonu • toplam 33,3 mg (çok dozluk)",
      "Kalite kontrolü: ≥%99 saflık (HPLC); endotoksin < 0,03 EU/mg; her flakonda orijinallik için kazı-kazan kod bulunur.",
    ],
  },
  {
    slug: "zptrop-16iu-1vial-zphc",
    name: "ZPtrop HGH ZPHC — 16 IU (1 lyophilized vial + bac water)",
    sku: "HGH16-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-16IU-1vial-1Bwater-ZPHC-4.jpg",
    sourcePriceUsd: 34.0,
    specs: [
      { label: "Standart rekonstitüsyon", value: "Ürünle verilen bakteriyostatik suyu ekleyin; somatropin berrak bir çözelti hâline gelene dek hafifçe çevirin.", kind: "spec" },
      { label: "Konsantrasyon", value: "Rekonstitüsyon sonrası flakon başına 16 IU (≈ toplam 5,3 mg); insülin enjektörleri ve mikro dozlama için uygundur.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Yağsız doku onarımı, yağ metabolizması modelleri, kolajen sentezi, toparlanma, uyku ve yaşlanma karşıtı çalışmalar.", kind: "claim" },
      { label: "Örnek Araştırma Dozu", value: "Günde 1–2 IU (genel iyilik hâli/onarım) • 2–3 IU (yağ kaybı modelleri) • 3–4 IU (hipertrofi protokolleri).", kind: "claim" },
      { label: "Saklama", value: "Tozu serin ve kuru tutun; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında saklayın; karıştırmadan sonra 7–10 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "ZPtrop İnsan Büyüme Hormonu — 191 aa rhGH",
      "16 IU liyofilize flakon + 1× bakteriyostatik su",
      "Kalite kontrolü: ≥%98–99 saflık (HPLC); düşük endotoksin profili; her flakon orijinallik ve tutarlılık için parti bazında doğrulanır.",
    ],
  },
  {
    slug: "zptrop-hgh-160iu-zphc",
    name: "ZPtrop HGH ZPHC — 160 IU (16 vials × 10 IU)",
    sku: "HGH160-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2019/03/zptrop-160-1.jpg",
    sourcePriceUsd: 279.0,
    specs: [
      { label: "Üretici", value: "ZPHC", kind: "spec" },
      { label: "Etkin Madde", value: "Somatropin", kind: "spec" },
      { label: "Konsantrasyon", value: "Flakon başına 16 IU (5,3 mg)", kind: "spec" },
      { label: "Hacim", value: "10 flakon", kind: "spec" },
      { label: "Form", value: "Bakteriyostatik su ile rekonstitüsyon için liyofilize toz", kind: "spec" },
      { label: "Kullanım Amacı", value: "Büyüme hormonu tedavisi, kas kütlesi kazanımı, yağ kaybı, yaşlanma karşıtı kullanım", kind: "claim" },
      { label: "Etki", value: "Kas kütlesinde artış, vücut yağında azalma, toparlanmada iyileşme ve yaşlanma karşıtı etkiler dâhil olmak üzere büyüme hormonu tedavisinin faydalarını desteklediği belirtilir.", kind: "claim" },
      { label: "Uygulama Yolu", value: "Rekonstitüsyon sonrası deri altı veya kas içi enjeksiyon", kind: "spec" },
      { label: "Önerilen Doz", value: "Sağlık profesyonelinin belirlediği dozlarda uygulanır; genellikle günde 2–10 IU aralığındadır.", kind: "claim" },
      { label: "Yan Etkiler", value: "Eklem ağrısı, su tutulumu, insülin direnci ve diyabet riskinde olası artış.", kind: "claim" },
      { label: "Saklama", value: "Serin, kuru ve ışıktan korunan bir yerde saklayın. Rekonstitüsyon sonrası buzdolabında muhafaza edin.", kind: "spec" },
    ],
    notes: [],
  },
  {
    slug: "zptrop-hgh-200iu-2x100iu-zphc",
    name: "ZPtrop HGH ZPHC — 200 IU (2 vials × 100 IU)",
    sku: "HGH200-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/01/zptrop-200iu-zphc-2-1.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Doz Rehberi", value: "Genel sağlık/yağ yakımı için günde 2–4 IU, kas kazanımı için 4–6 IU.", kind: "claim" },
      { label: "Soğuk zincirle taşınır", value: "Sıcaklık göstergeli yalıtımlı ambalajda 2–8 °C'de gönderilir.", kind: "claim" },
      { label: "Parti bazında test edilmiş kalite", value: "ZPHC kalite kontrolü: ≥%99 saflık, endotoksinsiz; orijinallik için kazı-kazan kod.", kind: "claim" },
    ],
    notes: [
      "Farma sınıfı ZPtrop HGH (191 aa somatropin) — 2 flakon × 100 IU",
      "Yağsız kas ve yağ kaybı sinerjisi: IGF-1'i artırdığı, toparlanmayı hızlandırdığı ve uyku kalitesini iyileştirdiği belirtilir.",
      "Saf 100 IU flakon: liyofilize toz berrak şekilde çözünür; bakteriyostatik su dâhildir.",
      "Gizlilik esaslı dünya çapında gönderim • çok dilli destek • güvenli ödeme.",
    ],
  },
  {
    slug: "zptrop-32iu-1vial-zphc",
    name: "ZPtrop HGH ZPHC — 32 IU (1 lyophilized vial + bac water)",
    sku: "HGH32-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-32IU-1vial-1Bwater-ZPHC-2.jpg",
    sourcePriceUsd: 65.0,
    specs: [
      { label: "Standart rekonstitüsyon", value: "Ürünle verilen bakteriyostatik suyu ekleyin; berrak bir somatropin çözeltisi için hafifçe çevirin.", kind: "spec" },
      { label: "Konsantrasyon", value: "Rekonstitüsyon sonrası flakon başına 32 IU (≈ toplam 10,7 mg); insülin enjektörleriyle uyumludur.", kind: "spec" },
      { label: "Araştırma Alanları", value: "Yağsız doku onarımı, yağ metabolizması modelleri, kolajen sentezi, uyku optimizasyonu, yaşlanma karşıtı yolaklar.", kind: "claim" },
      { label: "Örnek Araştırma Dozu", value: "Günde 2–4 IU (genel iyilik hâli/onarım) • 4–6 IU (yağ kaybı modelleri) • 6–8 IU (kas hipertrofisi protokolleri).", kind: "claim" },
      { label: "Saklama", value: "Tozu serin ve kuru tutun; sulandırılmış çözeltiyi 2–8 °C'de buzdolabında saklayın; karıştırmadan sonra 10–14 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "ZPtrop İnsan Büyüme Hormonu — 191 aa rhGH",
      "32 IU liyofilize flakon + 1× bakteriyostatik su",
      "Kalite kontrolü: ≥%98–99 saflık (HPLC); düşük endotoksin; her flakon doğrulanır ve orijinallik için parti bazında izlenir.",
    ],
  },
  {
    slug: "zptrop-150-aq-zphc-premixed",
    name: "Zptrop 150 AQ ZPHC - Premixed",
    sku: "HGH150-AQ-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-150IU-AQ-15IU-10VIAL-ZPHC-7.jpg",
    sourcePriceUsd: 237.0,
    specs: [
      { label: "Kullanıma hazır HGH", value: "Tutarlı etkinlik için steril sulu çözelti içinde tamamen hazır karışım rekombinant insan büyüme hormonu.", kind: "claim" },
      { label: "Somatotropik destek", value: "Kas onarımı, toparlanmanın iyileştirilmesi, yağ metabolizmasının güçlendirilmesi ve performans optimizasyonu üzerine araştırılmaktadır.", kind: "claim" },
      { label: "Rekonstitüsyon gerektirmez", value: "Her flakon, doğrudan kullanım için önceden çözülmüş, homojen 15 IU doz içerir.", kind: "claim" },
      { label: "Yüksek Saflıkta Formülasyon", value: "≥%99 saflık (HPLC); GMP ve ISO standartlarında üretilir, ZPHC kazı-kazan kod doğrulaması içerir.", kind: "spec" },
      { label: "Saklama", value: "2–8 °C'de buzdolabında saklayın; dondurmayın ve ışıktan koruyun.", kind: "spec" },
    ],
    notes: [
      "ZPtrop 150 AQ — ZPHC Pro-Line",
      "Hazır karışım HGH • 10 flakon × 15 IU (toplam 150 IU)",
      "Soğuk zincir ambalaj • kurcalamaya karşı korumalı flakonlar • gizlilik esaslı, takip edilebilir dünya çapında gönderim.",
    ],
  },
  {
    slug: "zptrop-hgh-zphc-90-iu-premixed",
    name: "Zptrop 90 AQ ZPHC - Premixed",
    sku: "HGH90-AQ-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2025/11/ZPTROP-90IU-KIT-ZPHC-2.jpg",
    sourcePriceUsd: 149.0,
    specs: [
      { label: "Kullanıma hazır formül", value: "Tamamen hazır karışım somatropin çözeltisi — rekonstitüsyon gerekmez; IU'yu doğrudan insülin enjektörüyle çekin.", kind: "claim" },
      { label: "Pratik dozlama", value: "Flakon başına 45 IU (≈ toplam 15 mg); sorunsuz çekim, tüm dozlarda tutarlı konsantrasyon.", kind: "claim" },
      { label: "Araştırma Alanları", value: "Doku onarımı, yağ metabolizması çalışmaları, kolajen sentezi, toparlanmanın güçlendirilmesi, uyku ve yaşlanma karşıtı modeller.", kind: "claim" },
      { label: "Örnek Araştırma Dozu", value: "Yatmadan önce 2–4 IU (toparlanma/yaşlanma karşıtı) • günde 4–6 IU (yağ kaybı) • günde 6–8 IU (hipertrofi).", kind: "claim" },
      { label: "Saklama", value: "Soğuk zincirle gönderilir; açıldıktan sonra 2–8 °C'de buzdolabında saklayın; soğukta tutulduğunda 28 gün stabildir.", kind: "spec" },
    ],
    notes: [
      "ZPtrop 90 AQ — 191 aa rhGH",
      "Hazır karışım somatropin • 2 × 45 IU sulu çözelti flakonu",
      "Kalite kontrolü: ≥%99 saflık (HPLC); çok düşük endotoksin; parti bazında izlenir ve orijinalliği doğrulanır.",
    ],
  },
  {
    slug: "zptrop-aq-180-iu-kit-5x36iu-pen-cartridges",
    name: "Zptrop AQ 180 IU Kit (5×36 IU Cartridges for Multi-Use Pen)",
    sku: "HGH180-AQ-CART-ZPHC",
    category: "hgh",
    peptideSlug: "hgh",
    image: "https://zphcstore.com/wp-content/uploads/2026/02/zptrop-aq-180iu-5-36iu-pen-cartridges-1.jpg",
    sourcePriceUsd: 299.0,
    specs: [
      { label: "Format", value: "Sıvı somatropin (191 aa, rDNA kaynaklı) içeren, uyumlu çok kullanımlık enjeksiyon kalemleri için tasarlanmış dolu tek hazneli kartuşlar.", kind: "spec" },
      { label: "Toplam İçerik", value: "Kit başına 180 IU (5 kartuş × 36 IU / her biri 12 mg).", kind: "spec" },
      { label: "Kullanıma hazır", value: "Rekonstitüsyon gerekmez; çok kullanımlık kalem sistemiyle hassas dozlama.", kind: "claim" },
      { label: "Araştırma Alanları", value: "Yağsız doku rejenerasyonu modelleri, yağ metabolizması yolakları, toparlanma protokolleri, kolajen sentezi ve uykuyla ilgili çalışmalar.", kind: "claim" },
      { label: "Örnek Araştırma Dozu", value: "Günde 2–4 IU (genel sağlık/toparlanma modelleri) • 4–6 IU (yağ metabolizması çalışmaları) • 6–8 IU (hipertrofi odaklı protokoller).", kind: "claim" },
      { label: "Saklama", value: "2–8 °C'de buzdolabında saklayın; ışıktan koruyun; dondurmayın.", kind: "spec" },
    ],
    notes: [
      "ZPtrop AQ 180 IU Kit — 191 aa rhGH (somatropin)",
      "Çok kullanımlık kalem için 5 × 36 IU tek hazneli kartuş",
      "Kalite kontrolü: yüksek saflıkta somatropin, steril farma sınıfı kartuşlar; parti bazında doğrulanmış ve orijinallik kontrollü.",
    ],
  },
]

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function productsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category)
}
